	[m0]\[[t]ˈɑːlɑː[/t]\] [p]adv[/p] [p]фр.[/p] à la[/m]
	[m1]1. [trn]а-ля; в стиле, в духе, во вкусе[/trn][/m]
	[m2][*][ex][lang id=1033]hairdo à la Marilyn Monroe[/lang] — причёска а-ля /под/ Мерилин Монро[/ex][/*][/m]
	[m2][*][ex][lang id=1033]à la Hollywood[/lang] — по-голливудски[/ex][/*][/m]
	[m2][*][ex][lang id=1033]demagoguery à la Hitler[/lang] — демагогия гитлеровского толка[/ex][/*][/m]
	[m1]2. [p]кул.[/p] [trn]приготовленный на какой-л. манер[/trn][/m]
	[m2][*][ex][lang id=1033]à la parisienne \[Boston\][/lang] — по-парижски \[по-бостонски\][/ex][/*][/m]
	[m2][*][ex][lang id=1033]lobster à la king[/lang] — омар «кинг» [com]([i]в белом соусе[/i])[/com][/ex][/*][/m]
	[m2][*][ex][lang id=1033]à la broche[/lang] — жаренный на вертеле[/ex][/*][/m]