	[m0][b][sup]1[/sup][/b][/m]
	[m1][b]Ⅰ[/b] \[[t]æz[/t] [com]([i]полная форма[/i])[/com]; [t]əz, z[/t] [com]([i]редуцированные формы[/i])[/com]\] [p]rel[/p] [p]pron[/p][/m]
	[m3]1. [com][i]вводит придаточные определительные предложения или обороты с[/i] [lang id=1033]such[/lang], [lang id=1033]the same[/lang] [c gray][i]{{[p]}}или{{[/p]}}[/i][/c] [lang id=1033]so[/lang] [i]в главном предложении[/i][/com] [trn]какой, который, как, что[/trn][/m]
	[m4][*][ex][lang id=1033]he came the same day as you[/lang] — он приехал в один день с вами[/ex][/*][/m]
	[m3]2. [com][i]вводит придаточные определительные предложения, относящиеся ко всему главному предложению[/i][/com] [trn]что, и это[/trn][/m]
	[m4][*][ex][lang id=1033]he was telling the truth, as you could see by his face[/lang] — он говорил правду, что /и это/ было видно по его лицу[/ex][/*][/m]
	[m1][b]Ⅱ[/b] \[[t]æz[/t] [com]([i]полная форма[/i])[/com]; [t]əz, z[/t] [com]([i]редуцированные формы[/i])[/com]\] [p]adv[/p][/m]
	[m3]1. [trn]как (например)[/trn][/m]
	[m4][*][ex][lang id=1033]some animals as the fox and the squirrel have bushy tails[/lang] — у некоторых животных, как (например) у лис и белок, пушистые хвосты[/ex][/*][/m]
	[m3]2. [trn]как, одинаково[/trn][/m]
	[m4][*][ex][lang id=1033]deaf as a post[/lang] — глухой как пень[/ex][/*][/m]
	[m4][*][ex][lang id=1033]late as usual[/lang] — опоздал как всегда[/ex][/*][/m]
	[m4][*][ex][lang id=1033]as such[/lang] — как таковой[/ex][/*][/m]
	[m4][*][ex][lang id=1033]man as man[/lang] — человек как таковой[/ex][/*][/m]
	[m3]3. [com][i]в сочетаниях[/i][/com]:[/m]
	[m4][*][ex][lang id=1033]as for[/lang] — что касается, что до[/ex][/*][/m]
	[m4][*][ex][lang id=1033]as for that book I don't like it[/lang] — что касается этой книги, то мне она не нравится[/ex][/*][/m]
	[m4][*][ex][lang id=1033]as from[/lang] — [p]канц.[/p] после; с такого-то числа[/ex][/*][/m]
	[m4][*][ex][lang id=1033]as from a date to be specified[/lang] — с даты, которая будет определена /установлена/ позднее[/ex][/*][/m]
	[m4][*][ex][lang id=1033]I'm resigning from the committee as from now[/lang] — я выхожу из состава комитета с сего числа[/ex][/*][/m]
	[m4][*][ex][lang id=1033]as much[/lang] — так[/ex][/*][/m]
	[m4][*][ex][lang id=1033]I thought as much[/lang] — я так и думал[/ex][/*][/m]
	[m4][*][ex][lang id=1033]as of[/lang] — [p]амер.[/p] = as for[/ex][/*][/m]
	[m4][*][ex][lang id=1033]as per[/lang] — [p]ком.[/p], [p]канц.[/p] согласно[/ex][/*][/m]
	[m4][*][ex][lang id=1033]as per order[/lang] — согласно заказу[/ex][/*][/m]
	[m4][*][ex][lang id=1033]as per copy enclosed[/lang] — согласно прилагаемой копии[/ex][/*][/m]
	[m4][*][ex][lang id=1033]as to[/lang] — а) относительно, о; [lang id=1033]he said nothing as to wages[/lang] — он ничего не сказал относительно заработной платы; б) что до, что касается[/ex][/*][/m]
	[m4][*][ex][lang id=1033]as to you, you can do whatever you like[/lang] — что касается вас, то можете делать всё, что хотите[/ex][/*][/m]
	[m4][*][ex][lang id=1033]I am not certain as to whether this is true[/lang] — я не уверен, правда это или нет[/ex][/*][/m]
	[m4][*][ex][lang id=1033]as well[/lang] — а) с таким же успехом; желательно, лучше; [lang id=1033]you may just as well stay[/lang] — вы можете с таким же успехом остаться; [lang id=1033]we might as well begin at once[/lang] — хорошо /лучше/ было бы начать сразу; [lang id=1033]you might as well go[/lang] — вы бы лучше пошли; б) также, к тому же; [lang id=1033]he takes English lessons on Mondays and Fridays as well[/lang] — он занимается английским по понедельникам, а также по пятницам[/ex][/*][/m]
	[m4][*][ex][lang id=1033]as yet[/lang] — до сих пор; пока ещё[/ex][/*][/m]
	[m4][*][ex][lang id=1033]there has been no change as yet[/lang] — пока ещё нет перемен[/ex][/*][/m]
	[m3][*][com][i]другие сочетания [p]см.[/p] под соответствующими словами[/i][/com][/*][/m]
	[m1][b]Ⅲ[/b] \[[t]æz[/t] [com]([i]полная форма[/i])[/com]; [t]əz, z[/t] [com]([i]редуцированные формы[/i])[/com]\] [p]cj[/p][/m]
	[m3]1. [com][i]в придаточных предложениях и обстоятельственных оборотах времени[/i] ([p]часто[/p] [lang id=1033]just as[/lang])[/com] [trn]когда; в то время как, по мере того как[/trn][/m]
	[m4][*][ex][lang id=1033]as I was coming here I lost my key[/lang] — когда я шёл сюда, я потерял ключ[/ex][/*][/m]
	[m4][*][ex][lang id=1033](just) as he finished his speech[/lang] — (как раз) в тот момент, когда он кончил говорить[/ex][/*][/m]
	[m4][*][ex][lang id=1033]she sang as she worked[/lang] — работая, она пела /напевала/[/ex][/*][/m]
	[m3]2. [com][i]в придаточных предложениях[/i][/com][/m]
	[m5]1) [com][i]причины[/i][/com] [trn]так как, поскольку, раз[/trn][/m]
	[m4][*][ex][lang id=1033]as I am here, I'd better stay[/lang] — раз я уже здесь, я лучше останусь[/ex][/*][/m]
	[m4][*][ex][lang id=1033]covered with dust as he was, he didn't want to come in[/lang] — он не хотел входить, так как был весь в пыли[/ex][/*][/m]
	[m5]2) [com][i]образа действия[/i][/com] [trn]как[/trn][/m]
	[m4][*][ex][lang id=1033]he will do as he likes[/lang] — он поступит /сделает/ как захочет[/ex][/*][/m]
	[m4][*][ex][lang id=1033]they rose as one man[/lang] — они поднялись все как один[/ex][/*][/m]
	[m3]3. [com][i]вводит обстоятельственные обороты сравнения[/i][/com] [trn]как; подобно тому как[/trn][/m]
	[m4][*][ex][lang id=1033]white as snow[/lang] — белый как снег \[[p]см.[/p] [p]тж[/p] <<as ... as>>\][/ex][/*][/m]
	[m4][*][ex][lang id=1033]in the same way as before[/lang] — как и раньше[/ex][/*][/m]
	[m4][*][ex][lang id=1033]do as I do[/lang] — делай как я[/ex][/*][/m]
	[m3]4. [com][i]вводит предикатив и [p]др.[/p] члены предложения со значением[/i][/com] [trn]как, в качестве[/trn]; [com][i]передаётся [p]тж[/p] [p]твор.[/p] падежом[/i][/com][/m]
	[m4][*][ex][lang id=1033]to work as teacher \[as judge\][/lang] — работать учителем \[судьёй\][/ex][/*][/m]
	[m4][*][ex][lang id=1033]he introduced her as his sister[/lang] — он представил её как свою сестру[/ex][/*][/m]
	[m4][*][ex][lang id=1033]he appeared as King Lear[/lang] — он выступил в роли короля Лира[/ex][/*][/m]
	[m4][*][ex][lang id=1033]it is regarded as an accident[/lang] — это рассматривается как несчастный случай[/ex][/*][/m]
	[m4][*][ex][lang id=1033]as a very old friend of your father[/lang] — как старый друг вашего отца[/ex][/*][/m]
	[m4][*][ex][lang id=1033]he meant it as a joke[/lang] — он сказал это в шутку[/ex][/*][/m]
	[m3]5. [com]([i]в сочетании с[/i] [lang id=1033]so[/lang]) [i]вводит инфинитив результата и цели[/i][/com] [trn]чтобы; что[/trn][/m]
	[m4][*][ex][lang id=1033]he is not so foolish as to do that[/lang] — он не так глуп, чтобы сделать это[/ex][/*][/m]
	[m4][*][ex][lang id=1033]be so good as to send it to me[/lang] — будьте добры прислать это мне[/ex][/*][/m]
	[m3]6. [com][i]употребляется во вводных словах и предложениях[/i][/com] [trn]как[/trn][/m]
	[m4][*][ex][lang id=1033]as you know[/lang] — как вы знаете, как известно[/ex][/*][/m]
	[m4][*][ex][lang id=1033]as seems better to you[/lang] — как вам кажется лучше[/ex][/*][/m]
	[m4][*][ex][lang id=1033]as is common /customary/[/lang] — как принято[/ex][/*][/m]
	[m4][*][ex][lang id=1033]as it happens[/lang] — оказывается, между прочим[/ex][/*][/m]
	[m4][*][ex][lang id=1033]as it happens he is a friend of mine[/lang] — между прочим, он мой друг[/ex][/*][/m]
	[m4][*][ex][lang id=1033]they were looking for a flat, as arranged[/lang] — как было условлено, они искали квартиру[/ex][/*][/m]
	[m3]7. [com][i]в сочетаниях[/i][/com]:[/m]
	[m4][*][ex][lang id=1033]as against[/lang] — по сравнению[/ex][/*][/m]
	[m4][*][ex][lang id=1033]the business done this year amounts to £20,000 as against £15,000 last year[/lang] — в этом году мы выполнили заказов на 20 тысяч фунтов стерлингов по сравнению с 15 тысячами фунтов стерлингов в прошлом году[/ex][/*][/m]
	[m4][*][ex][lang id=1033]as if[/lang] — словно, как будто[/ex][/*][/m]
	[m4][*][ex][lang id=1033]he looks as if he had seen a ghost[/lang] — у него такой вид, словно привидение увидел[/ex][/*][/m]
	[m4][*][ex][lang id=1033]as if you didn't know that![/lang] — уж будто бы вы этого не знали \[[p]см.[/p] [p]тж[/p] <<as if>>\][/ex][/*][/m]
	[m4][*][ex][lang id=1033]as it is[/lang] — в действительности, и так; однако[/ex][/*][/m]
	[m4][*][ex][lang id=1033]we hoped things would get better but as it is they are getting worse[/lang] — мы надеялись, что положение улучшится, но в действительности оно ухудшается[/ex][/*][/m]
	[m4][*][ex][lang id=1033]you have too many friends as it is[/lang] — у вас и так слишком много друзей[/ex][/*][/m]
	[m4][*][ex][lang id=1033]bad as it is, it could be worse[/lang] — как это ни плохо, однако могло быть и хуже[/ex][/*][/m]
	[m4][*][ex][lang id=1033]as is[/lang] — а) [p]разг.[/p] как есть; в том состоянии, в котором что-л. находится; [lang id=1033]we bought the table as is[/lang] — мы купили стол, как он есть; б) [p]ком.[/p] без гарантии качества; [lang id=1033]as is sale[/lang] — продажа товара на условии «как есть», без гарантии качества[/ex][/*][/m]
	[m4][*][ex][lang id=1033]as it stands[/lang] — без перемен, так[/ex][/*][/m]
	[m4][*][ex][lang id=1033]as it stands, it is good enough[/lang] — в таком виде это не так уж плохо[/ex][/*][/m]
	[m4][*][ex][lang id=1033]as it was[/lang] — как ни, хотя[/ex][/*][/m]
	[m4][*][ex][lang id=1033]tired as they were, they continued their way[/lang] — как они ни устали /хотя они очень устали/, они продолжали свой путь[/ex][/*][/m]
	[m4][*][ex][lang id=1033]strange as it may seem[/lang] — как ни странно[/ex][/*][/m]
	[m4][*][ex][lang id=1033]try as they would[/lang] — как бы они ни старались[/ex][/*][/m]
	[m4][*][ex][lang id=1033]she was near enough to tears as it was[/lang] — она и без того чуть не плакала[/ex][/*][/m]
	[m4][*][ex][lang id=1033]as … so[/lang] — как … так (и)[/ex][/*][/m]
	[m4][*][ex][lang id=1033]as [com][i]A[/i][/com] is to [com][i]B[/i][/com] so [com][i]B[/i][/com] is to [com][i]C[/i][/lang] — [i]A[/i][/com] относится к [com][i]B[/i][/com], как [com][i]B[/i][/com] относится к [com][i]C[/i][/com][/ex][/*][/m]
	[m4][*][ex][lang id=1033]as fire warms the body so does kindness warm the heart[/lang] — огонь согревает тело, доброта — душу[/ex][/*][/m]
	[m4][*][ex][lang id=1033]as you treat me, so will I treat you[/lang] — как вы относитесь ко мне, так и я буду относиться к вам[/ex][/*][/m]
	[m4][*][ex][lang id=1033]as though[/lang] = <<as if>>[/ex][/*][/m]
	[m4][*][ex][lang id=1033]it looks as though it might rain[/lang] — похоже, (что) пойдёт дождь[/ex][/*][/m]
	[m4][*][ex][p]♦[/p] [lang id=1033]as you were![/lang] — [p]воен.[/p] отставить![/ex][/*][/m]
	[m4][*][ex][lang id=1033]as you do![/lang] — [p]мор.[/p] так держать! [com]([i]команда[/i])[/com][/ex][/*][/m]
	[m4][*][ex][lang id=1033]as who should say[/lang] — [p]арх.[/p] так сказать; если можно так выразиться[/ex][/*][/m]
	[m4][*][ex][lang id=1033]as things, persons go[/lang] — что касается чего-л., кого-л.[/ex][/*][/m]
	[m4][*][ex][lang id=1033]he is quite well-behaved as boys go[/lang] — для мальчика он довольно хорошо себя ведёт[/ex][/*][/m]
	[m4][*][ex][lang id=1033]it was very cheap as prices of cars go[/lang] — учитывая нынешние цены на автомобили, мы купили машину дёшево[/ex][/*][/m]
	[m0][b][sup]2[/sup][/b][/m]
	[m0]\[[t]æs[/t]\] [p]n[/p] [com]([p]pl[/p] [lang id=1033]asses[/lang][/com] \[[t]ˈæsiːz[/t]\]) [p]ист.[/p][/m]
	[m2]1. [trn]ас[/trn] [com]([i]древнеримская мера веса[/i])[/com][/m]
	[m2]2. [trn]ас[/trn] [com]([i]древнеримская бронзовая монета[/i])[/com][/m]