	[m0][b]Ⅰ[/b] \[[t]hæv[/t]\] [p]n[/p][/m]
	[m2]1. [p]pl[/p] [trn]имущие[/trn][/m]
	[m3][*][ex][lang id=1033]the haves and have-nots[/lang] — богатые и бедные; имущие и неимущие [com]([i]люди, классы, страны[/i])[/com][/ex][/*][/m]
	[m2]2. [p]разг.[/p] [trn]обман, надувательство[/trn][/m]
	[m0][b]Ⅱ[/b] \[[t]hæv[/t] [com]([i]полная форма[/i])[/com]; [t]həv, əv[/t], [p]v[/p] [com]([i]редуцированные формы[/i])[/com]\] [p]v[/p] [com]([lang id=1033]had[/lang]; [p]3-е[/p] [p]л.[/p] [p]ед.[/p] [p]ч.[/p] [p]наст.[/p] [p]вр.[/p] [lang id=1033]has[/lang] [c gray][i]{{[p]}}или{{[/p]}}[/i][/c] [p]арх.[/p] [lang id=1033]hath[/lang]; [p]арх.[/p] [p]2-е[/p] [p]л.[/p] [p]ед.[/p] [p]ч.[/p] [p]наст.[/p] [p]вр.[/p] [lang id=1033]hast,[/lang] [p]арх.[/p] [p]2-е[/p] [p]л.[/p] [p]ед.[/p] [p]ч.[/p] [p]прош.[/p] [p]вр.[/p] [lang id=1033]hadst, haddest[/lang])[/com][/m]
	[m2][c][b]Ⅰ[/b][/c][/m]
	[m2]1. [trn]иметь[/trn][/m]
	[m3][*][ex][lang id=1033]he has (got) a family \[a friend, a flat\][/lang] — у него (есть) семья \[друг, квартира\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]I have many books \[no money\][/lang] — у меня много книг \[нет денег\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]all I have[/lang] — всё, что у меня есть[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to have shares in a company[/lang] — быть держателем акций какой-л. компании[/ex][/*][/m]
	[m3][*][ex][lang id=1033]has the house a garden?[/lang] — есть ли при (этом) доме сад?[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the door has no key to it[/lang] — к этой двери нет ключа[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the bag had no name on it[/lang] — на сумке не было наклейки /бирки/ с фамилией[/ex][/*][/m]
	[m3][*][ex][lang id=1033]have you time to come with me?[/lang] — у вас есть время (чтобы) пойти со мной?[/ex][/*][/m]
	[m3][*][ex][lang id=1033]do you have much time for reading?[/lang] — у тебя остаётся много времени для чтения?[/ex][/*][/m]
	[m3][*][ex][lang id=1033]I have no words to express …[/lang] — у меня не хватает слов, чтобы выразить …[/ex][/*][/m]
	[m3][*][ex][lang id=1033]I have nothing to do[/lang] — мне нечего делать /нечем заняться/[/ex][/*][/m]
	[m3][*][ex][lang id=1033]there was no work to be had[/lang] — работу невозможно было найти[/ex][/*][/m]
	[m3][*][ex][lang id=1033]I had my work to do[/lang] — мне надо было (ещё) сделать работу; у меня ещё была работа[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to have smb on one's side[/lang] — иметь поддержку с чьей-л. стороны[/ex][/*][/m]
	[m3][*][ex][lang id=1033]she has the law on her side[/lang] — закон на её стороне[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to have and to hold[/lang] — [p]юр.[/p] передаётся в собственность и владение [com]([i]в документах о передаче имущества[/i])[/com][/ex][/*][/m]
	[m2]2. [trn]обладать, иметь[/trn][/m]
	[m3][*][ex][lang id=1033]to have much \[little\] in common with smb[/lang] — иметь много \[мало\] общего с кем-л.[/ex][/*][/m]
	[m3][*][ex][lang id=1033]he has blue eyes \[a bad memory\][/lang] — у него синие глаза \[плохая память\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]he has (got) an ear for music \[a fine taste, perfect health\][/lang] — у него хороший (музыкальный) слух \[прекрасный вкус, великолепное здоровье\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]she had faith in him[/lang] — она верила ему /в него/[/ex][/*][/m]
	[m3][*][ex][lang id=1033]these strawberries have a beautiful flavour[/lang] — у этой клубники чудесный аромат[/ex][/*][/m]
	[m3][*][ex][lang id=1033]he has a sense of humour[/lang] — он не лишён чувства юмора[/ex][/*][/m]
	[m2]3. [trn]состоять из; иметь в качестве составной [c gray][i]{{[p]}}или{{[/p]}}[/i][/c] неотъемлемой части[/trn][/m]
	[m3][*][ex][lang id=1033]the book has 300 pages[/lang] — в этой книге 300 страниц[/ex][/*][/m]
	[m3][*][ex][lang id=1033]May has 31 days[/lang] — в мае 31 день[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the house has three storeys[/lang] — в этом доме три этажа[/ex][/*][/m]
	[m2]4. 1) [trn]получать[/trn][/m]
	[m3][*][ex][lang id=1033]to have one's wish[/lang] — получить желаемое[/ex][/*][/m]
	[m3][*][ex][lang id=1033]he had a letter \[a telegram, a parcel\][/lang] — он получил письмо \[телеграмму, посылку\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]they had no news of him[/lang] — они не получали о нём известий, они ничего не слышали о нём[/ex][/*][/m]
	[m3][*][ex][lang id=1033]let me have your order as soon as possible[/lang] — пришлите мне ваш заказ как можно скорее[/ex][/*][/m]
	[m3][*][ex][lang id=1033]he has had a rough lesson[/lang] — он получил жестокий урок[/ex][/*][/m]
	[m3][*][ex][lang id=1033]you have my sympathy[/lang] — я вам сочувствую[/ex][/*][/m]
	[m3][*][ex][lang id=1033]you have my apologies[/lang] — (я) приношу (вам) свои извинения[/ex][/*][/m]
	[m4]2) [trn]приобретать[/trn][/m]
	[m3][*][ex][lang id=1033]it is to be had at the chemist's[/lang] — это можно получить /купить/ в аптеке[/ex][/*][/m]
	[m3][*][ex][lang id=1033]you may have it for five pounds[/lang] — вы можете получить /купить/ это за пять фунтов[/ex][/*][/m]
	[m3][*][ex][lang id=1033]I'll let you have it for five pounds[/lang] — я отдам /уступлю/ это за пять фунтов[/ex][/*][/m]
	[m3][*][ex][lang id=1033]which book will you have?[/lang] — какую книгу вы хотите /возьмёте/?[/ex][/*][/m]
	[m4]3) [trn]узнавать[/trn][/m]
	[m3][*][ex][lang id=1033]they had it from your neighbour \[from his own mouth\][/lang] — они узнали это /получили сообщение об этом/ от вашего соседа \[от него самого\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]he had it on good authority[/lang] — он узнал об этом из достоверных источников[/ex][/*][/m]
	[m3][*][ex][lang id=1033]he wants to have your name[/lang] — он хочет узнать ваше имя[/ex][/*][/m]
	[m4]4) [trn]добиваться[/trn][/m]
	[m3][*][ex][lang id=1033]he was determined to have an answer[/lang] — он решил добиться ответа[/ex][/*][/m]
	[m3][*][ex][lang id=1033]there is nothing to be had here[/lang] — здесь ничего не добьёшься /не получишь/[/ex][/*][/m]
	[m4]5) [trn]зарабатывать[/trn][/m]
	[m3][*][ex][lang id=1033]he has ten thousand pounds a year[/lang] — он получает /зарабатывает/ десять тысяч фунтов (стерлингов) в год[/ex][/*][/m]
	[m2]5. [trn]находиться; иметься[/trn][/m]
	[m3][*][ex][lang id=1033]he had the river on his left[/lang] — слева от него была река[/ex][/*][/m]
	[m3][*][ex][lang id=1033]you have a fireplace on your right[/lang] — справа от вас камин[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the committee has a report before it[/lang] — комитету представлен доклад[/ex][/*][/m]
	[m2]6. [trn]происходить, случаться[/trn][/m]
	[m3][*][ex][lang id=1033]we had an earthquake last month[/lang] — в прошлом месяце у нас было землетрясение[/ex][/*][/m]
	[m3][*][ex][lang id=1033]we have had much rain \[fine weather\] this year[/lang] — у нас в этом году было много дождей \[стояла прекрасная погода\][/ex][/*][/m]
	[m2]7. [trn]знать; уметь[/trn][/m]
	[m3][*][ex][lang id=1033]he has small Latin and less Greek[/lang] — он плохо знает латынь и ещё хуже греческий[/ex][/*][/m]
	[m2]8. [p]разг.[/p] [trn]усваивать, понимать; найти решение[/trn][/m]
	[m3][*][ex][lang id=1033]I have it![/lang] — придумал /нашёл/![/ex][/*][/m]
	[m3][*][ex][lang id=1033]now I have your idea[/lang] — теперь я понял вашу мысль[/ex][/*][/m]
	[m3][*][ex][lang id=1033]you have me?[/lang] — вы меня поняли?; вам ясно?[/ex][/*][/m]
	[m2]9. [trn]взять в жёны [c gray][i]{{[p]}}или{{[/p]}}[/i][/c] мужья[/trn][/m]
	[m3][*][ex][lang id=1033]if she will have him[/lang] — если она согласится выйти за него[/ex][/*][/m]
	[m3][*][ex][lang id=1033]and now he won't have her[/lang] — а теперь он не хочет на ней жениться[/ex][/*][/m]
	[m2]10. 1) [trn]принимать[/trn] [com]([i]кого-л. в качестве гостя[/i] [p]и т. п.[/p])[/com][/m]
	[m3][*][ex][lang id=1033]to have smb (in) to dinner[/lang] — пригласить кого-л. (к себе) на обед[/ex][/*][/m]
	[m3][*][ex][lang id=1033]yesterday he had two visitors[/lang] — вчера у него было два посетителя[/ex][/*][/m]
	[m3][*][ex][lang id=1033]we don't have many visitors[/lang] — у неё редко бывают гости[/ex][/*][/m]
	[m3][*][ex][lang id=1033]we are having them down for the weekend /over the Sunday/[/lang] — мы пригласили их на выходные /провести с нами выходные/[/ex][/*][/m]
	[m3][*][ex][lang id=1033]we would rather stay with you, if you will have us[/lang] — мы хотели бы остановиться у вас, если вы согласны (нас принять)[/ex][/*][/m]
	[m4]2) [trn]взять, принять[/trn] [com]([i]в друзья, в ученики[/i] [p]и т. п.[/p])[/com][/m]
	[m3][*][ex][lang id=1033]would you like to have such a man for a friend?[/lang] — вы бы хотели видеть /считать/ такого человека своим другом?[/ex][/*][/m]
	[m2]11. [p]разг.[/p][/m]
	[m4]1) [trn]одолеть, взять верх, победить[/trn] [com]([p]тж[/p] [lang id=1033]have it[/lang])[/com][/m]
	[m3][*][ex][lang id=1033]mind he doesn't have you![/lang] — смотри, чтобы он тебя не одолел![/ex][/*][/m]
	[m3][*][ex][lang id=1033]he had you completely in the first round[/lang] — в первом же раунде он победил вас[/ex][/*][/m]
	[m3][*][ex][lang id=1033]he had you there[/lang] — тут-то вы ему и попались[/ex][/*][/m]
	[m3][*][ex][lang id=1033]that's where I shall have him![/lang] — вот чем я его возьму!, тут-то я его обойду!, тут-то он и попадётся![/ex][/*][/m]
	[m3][*][ex][lang id=1033]the “ayes” have it[/lang] — голосовавшие «за» оказались в большинстве[/ex][/*][/m]
	[m4]2) [trn]обмануть, обойти, перехитрить[/trn][/m]
	[m3][*][ex][lang id=1033]I'm afraid you have been had[/lang] — боюсь, что вас обманули /провели/[/ex][/*][/m]
	[m3][*][ex][lang id=1033]I'm not to be had[/lang] — меня не проведёшь[/ex][/*][/m]
	[m2]12. [p]сл.[/p] [trn]обладать[/trn][/m]
	[m3][*][ex][lang id=1033]to have a woman[/lang] — обладать женщиной[/ex][/*][/m]
	[m2][c][b]Ⅱ А[/b][/c][/m]
	[m2]1. [trn]проводить[/trn] [com]([i]время[/i])[/com][/m]
	[m3][*][ex][lang id=1033]he wants to have a pleasant evening[/lang] — он хочет приятно провести вечер[/ex][/*][/m]
	[m3][*][ex][lang id=1033]I've had a real good time[/lang] — я замечательно провёл время[/ex][/*][/m]
	[m3][*][ex][lang id=1033]have a good time /some fun/![/lang] — желаю тебе повеселиться /приятно провести время/![/ex][/*][/m]
	[m3][*][ex][lang id=1033]they have had a somewhat agitating day[/lang] — этот день прошёл для них в волнении, они пережили очень много волнений в этот день[/ex][/*][/m]
	[m3][*][ex][lang id=1033]she has had a bad night[/lang] — она плохо спала в эту ночь; ночью ей было плохо[/ex][/*][/m]
	[m2]2. [trn]принимать [com]([i]пищу[/i] [p]и т. п.[/p])[/com]; есть, пить[/trn][/m]
	[m3][*][ex][lang id=1033]I have dinner at three[/lang] — я обедаю в три (часа)[/ex][/*][/m]
	[m3][*][ex][lang id=1033]do you have tea or coffee for breakfast?[/lang] — вы за завтраком пьёте чай или кофе?[/ex][/*][/m]
	[m3][*][ex][lang id=1033]what will you have?[/lang] — что вы будете пить /есть/?[/ex][/*][/m]
	[m3][*][ex][lang id=1033]will you have another cup of tea?[/lang] — не выпьете ли вы ещё чашку чаю?[/ex][/*][/m]
	[m3][*][ex][lang id=1033]have some more sauce[/lang] — возьмите ещё соуса[/ex][/*][/m]
	[m3][*][ex][lang id=1033]what can you let me have?[/lang] — что у вас найдётся поесть?, что вы можете мне предложить? [com]([i]в ресторане, кафе[/i] [p]и т. п.[/p])[/com][/ex][/*][/m]
	[m3][*][ex][lang id=1033]I'll have ice cream and coffee[/lang] — мне, пожалуйста, мороженое и кофе [com]([i]обращение к официанту[/i])[/com][/ex][/*][/m]
	[m3][*][ex][lang id=1033]let me have some more meat[/lang] — дайте мне ещё мяса[/ex][/*][/m]
	[m3][*][ex][lang id=1033]have a cigar?[/lang] — хотите сигару?[/ex][/*][/m]
	[m2]3. [trn]родить; приносить [com]([i]потомство[/i])[/com]; иметь[/trn] [com]([i]детей[/i])[/com][/m]
	[m3][*][ex][lang id=1033]she's going to have a baby[/lang] — у неё будет ребёнок[/ex][/*][/m]
	[m3][*][ex][lang id=1033]she had the baby in April[/lang] — она родила в апреле[/ex][/*][/m]
	[m3][*][ex][lang id=1033]he had had two children by her \[by a previous marriage\][/lang] — у него от неё \[от прежнего брака\] двое детей[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the dog had four puppies[/lang] — собака принесла четырёх щенят[/ex][/*][/m]
	[m2]4. [trn]держать[/trn] [com]([i]кого-л. в своей власти[/i] [p]и т. п.[/p])[/com][/m]
	[m3][*][ex][lang id=1033]she had him in her power[/lang] — он был у неё в руках[/ex][/*][/m]
	[m2]5. [trn]переживать[/trn] [com]([i]события[/i] [p]и т. п.[/p])[/com][/m]
	[m3][*][ex][lang id=1033]she had an odd experience[/lang] — с ней произошёл /приключился/ странный случай[/ex][/*][/m]
	[m3][*][ex][lang id=1033]they had quite an adventure[/lang] — у них было настоящее приключение[/ex][/*][/m]
	[m3][*][ex][lang id=1033]she has a lot of trouble[/lang] — у неё масса неприятностей[/ex][/*][/m]
	[m3][*][ex][lang id=1033]be didn't have any trouble in finding the book[/lang] — он нашёл книгу без (всякого) труда[/ex][/*][/m]
	[m2]6. [trn]ощущать, испытывать [com]([i]боль[/i])[/com]; переносить[/trn] [com]([i]заболевание[/i])[/com][/m]
	[m3][*][ex][lang id=1033]she has a headache \[toothache, a sore throat\][/lang] — у неё болит голова \[зуб, горло\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]he has measles \[typhus\][/lang] — у него корь \[тиф\], он болен корью \[тифом\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]she has a bad cold (in the head)[/lang] — у неё сильный насморк[/ex][/*][/m]
	[m2]7. [trn]проявлять, испытывать[/trn] [com]([i]чувства[/i] [p]и т. п.[/p])[/com][/m]
	[m3][*][ex][lang id=1033]to have pity \[compassion\] for smb[/lang] — проявлять жалость \[сострадание\] к кому-л.[/ex][/*][/m]
	[m3][*][ex][lang id=1033]he has patience with children[/lang] — он терпелив с детьми[/ex][/*][/m]
	[m3][*][ex][lang id=1033]he has indulgence for mistakes[/lang] — он снисходителен к ошибкам[/ex][/*][/m]
	[m3][*][ex][lang id=1033]if you had any real affection[/lang] — если бы у вас было настоящее чувство[/ex][/*][/m]
	[m3][*][ex][lang id=1033]have no doubt[/lang] — можете не сомневаться[/ex][/*][/m]
	[m3][*][ex][lang id=1033]have no fear![/lang] — не бойтесь!, не бойся![/ex][/*][/m]
	[m3][*][ex][lang id=1033]has she really the cheek to ask for more money?[/lang] — неужели у неё хватило нахальства просить ещё денег?[/ex][/*][/m]
	[m3][*][ex][lang id=1033]please have the goodness /kindness/ to ring him up[/lang] — будьте столь любезны, позвоните ему[/ex][/*][/m]
	[m3][*][ex][lang id=1033]he had the kindness to assent …[/lang] — он любезно согласился …, он был так любезен, что согласился …[/ex][/*][/m]
	[m2]8. [trn]быть наделённым[/trn] [com]([i]властью, правом[/i] [p]и т. п.[/p])[/com][/m]
	[m3][*][ex][lang id=1033]he has (got) authority \[privilege\][/lang] — он пользуется авторитетом \[привилегией\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]he has charge of …[/lang] — а) он заботится о …; б) в его ведении находится …[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to have responsibility for smth[/lang] — а) нести ответственность за что-л.; б) быть виноватым в чём-л.[/ex][/*][/m]
	[m2]9. [trn]приводить [com]([i]к какому-л. результату[/i])[/com]; оказывать[/trn] [com]([i]воздействие[/i])[/com][/m]
	[m3][*][ex][lang id=1033]this policy had the desired effect[/lang] — эта политика привела к желаемым результатам[/ex][/*][/m]
	[m2]10. [trn]иметь[/trn] [com]([i]представление, мнение, право[/i] [p]и т. п.[/p])[/com][/m]
	[m3][*][ex][lang id=1033]have you any idea where he lives?[/lang] — не знаете ли вы, где он живёт?[/ex][/*][/m]
	[m3][*][ex][lang id=1033]I have no idea where he may be at present[/lang] — я не имею ни малейшего представления (о том), где он сейчас может быть[/ex][/*][/m]
	[m3][*][ex][lang id=1033]he has an opinion …[/lang] — он считает …[/ex][/*][/m]
	[m2][c][b]Ⅱ Б[/b][/c][/m]
	[m2]1. [com][i][lang id=1033]to have smb[/lang][/i] ([i][lang id=1033]to[/lang][/i]) [i][lang id=1033]do /doing/ smth[/lang][/i][/com] [trn]заставить кого-л. сделать что-л.; устроить [c gray][i]{{[p]}}или{{[/p]}}[/i][/c] сделать так, чтобы кто-л. сделал что-л.[/trn][/m]
	[m3][*][ex][lang id=1033]I will have him come[/lang] — я заставлю его прийти, я сделаю так /распоряжусь/, чтобы он пришёл[/ex][/*][/m]
	[m3][*][ex][lang id=1033]we ought to have the doctor examine her[/lang] — нам следовало бы показать её врачу[/ex][/*][/m]
	[m3][*][ex][lang id=1033]she had us all guessing what her next move would be[/lang] — мы все старались угадать, что она сделает /как она поступит/ дальше[/ex][/*][/m]
	[m3][*][ex][lang id=1033]I would have you to know …[/lang] — я хотел бы поставить вас в известность …, я бы хотел, чтобы вы знали …[/ex][/*][/m]
	[m3][*][ex][lang id=1033]will you have me to help you?[/lang] — вы хотите, чтобы я вам помог?[/ex][/*][/m]
	[m2]2. [com][i][lang id=1033]to have smth done[/lang][/i][/com][/m]
	[m4]1) [com]([i]выражает действие, совершённое по инициативе или побуждению какого-л. лица[/i])[/com] [trn]велеть, приказать сделать что-л. для себя[/trn][/m]
	[m3][*][ex][lang id=1033]he had his hair cut[/lang] — он постригся[/ex][/*][/m]
	[m3][*][ex][lang id=1033]we have had our photos taken[/lang] — мы сфотографировались[/ex][/*][/m]
	[m3][*][ex][lang id=1033]he had a tooth taken out[/lang] — ему удалили зуб[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the town council has had ten houses built[/lang] — городской совет построил десять домов[/ex][/*][/m]
	[m4]2) [com]([i]выражает действие, совершённое помимо воли или желания какого-л. лица и направленное на него или на какой-л. предмет[/i])[/com] [trn]подвергнуться какому-л. действию[/trn][/m]
	[m3][*][ex][lang id=1033]I have had my money stolen[/lang] — у меня украли деньги[/ex][/*][/m]
	[m3][*][ex][lang id=1033]he had his leg broken[/lang] — он сломал себе ногу[/ex][/*][/m]
	[m3][*][ex][lang id=1033]I never had my word doubted[/lang] — до сих пор мне всегда верили[/ex][/*][/m]
	[m3][*][ex][lang id=1033]we had a note handed to us[/lang] — нам передали письмо[/ex][/*][/m]
	[m3][*][ex][lang id=1033]three houses had their windows shattered[/lang] — в трёх домах разбились /вылетели/ стёкла[/ex][/*][/m]
	[m2]3. [com][i]to have smth в сочетании с прилагательным или наречием[/i][/com][/m]
	[m4]1) [trn]сделать [c gray][i]{{[p]}}или{{[/p]}}[/i][/c] устроить так, чтобы что-л. оказалось таким-то [c gray][i]{{[p]}}или{{[/p]}}[/i][/c] там-то[/trn][/m]
	[m3][*][ex][lang id=1033]to have smb up[/lang] — заставить кого-л. подняться (наверх) \[[p]ср.[/p] [p]тж[/p] <<have up>>\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]let's have her down[/lang] — пусть она сойдёт /спустится/ к нам[/ex][/*][/m]
	[m3][*][ex][lang id=1033]I'll have everything ready[/lang] — у меня всё будет готово[/ex][/*][/m]
	[m3][*][ex][lang id=1033]she had a tooth out[/lang] — ей удалили зуб[/ex][/*][/m]
	[m3][*][ex][lang id=1033]can we have our ball back, please?[/lang] — отдайте нам, пожалуйста, мяч[/ex][/*][/m]
	[m4]2) [trn]быть в определённом состоянии[/trn][/m]
	[m3][*][ex][lang id=1033]he had his eyes open[/lang] — глаза у него были открыты[/ex][/*][/m]
	[m3][*][ex][lang id=1033]he had his hands full[/lang] — руки у него были заняты[/ex][/*][/m]
	[m2]4. [com][i][lang id=1033]to have to do with smb, smth[/lang][/i][/com] [trn]иметь отношение к кому-л., чему-л.[/trn][/m]
	[m3][*][ex][lang id=1033]this has nothing to do with you[/lang] — к вам это никакого отношения не имеет, вас это (никак) не касается[/ex][/*][/m]
	[m3][*][ex][lang id=1033]I advise you to have nothing to do with that man[/lang] — я вам советую не иметь никаких дел с этим человеком[/ex][/*][/m]
	[m2]5. [com][i][lang id=1033]to have smth about /on/ one[/lang][/i][/com] [trn]иметь что-л. при себе, с собой[/trn][/m]
	[m3][*][ex][lang id=1033]he hadn't any money \[papers\] about /on/ him[/lang] — у него не было при себе /с собой/ денег \[документов\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]have you the time on you?[/lang] — у вас есть при себе часы?[/ex][/*][/m]
	[m2]6. [com][i][lang id=1033]to have smth against smb[/lang][/i][/com] [trn]иметь что-л. против кого-л.[/trn][/m]
	[m3][*][ex][lang id=1033]what have you against it \[him\]?[/lang] — что вы имеете против этого \[него\]?[/ex][/*][/m]
	[m3][*][ex][lang id=1033]I have nothing against it \[him\][/lang] — я не имею ничего против этого \[него\][/ex][/*][/m]
	[m2]7. [com][i][lang id=1033]to have smth on smb[/lang][/i][/com] [trn]знать о ком-л. что-л. плохое, дурное[/trn][/m]
	[m3][*][ex][lang id=1033]he has (got) nothing on me[/lang] — он обо мне ничего дурного не знает; у него нет никаких улик против меня[/ex][/*][/m]
	[m2]8. [com][i][lang id=1033]to have smb, smth on smb[/lang][/i][/com] [trn]напускать кого-л., что-л. на кого-л.; науськивать[/trn][/m]
	[m3][*][ex][lang id=1033]to have the law \[the police\] on smb[/lang] — подать в суд \[заявить в полицию\] на кого-л.[/ex][/*][/m]
	[m2]9. [com][i][lang id=1033]to have at smb[/lang][/i][/com] [trn]налетать, напускаться на кого-л.[/trn][/m]
	[m3][*][ex][lang id=1033](let us) have at him[/lang] — за ним (в погоню)![/ex][/*][/m]
	[m3][*][ex][lang id=1033]to have a go /a shy, a shot, a bash, a stab/ at smth, smb[/lang] — сделать попытку [com]([i]сделать[/i] [p]что-л.[/p])[/com]; пробовать что-л., пробовать силы на чём-л., на ком-л.[/ex][/*][/m]
	[m2]10. [com][i][lang id=1033]one had better /best/ do smth[/lang][/i][/com] [trn]лучше бы вам /тебе, ему [p]и т. п.[/p]/ сделать что-л., вы бы /ты бы, он бы [p]и т. п.[/p]/ лучше[/trn] …[/m]
	[m3][*][ex][lang id=1033]you had better ask him about it[/lang] — лучше бы тебе /вам/ спросить его об этом[/ex][/*][/m]
	[m3][*][ex][lang id=1033]you'd better go home and rest[/lang] — пошёл бы ты лучше домой отдыхать[/ex][/*][/m]
	[m3][*][ex][lang id=1033]you had best go at once[/lang] — тебе лучше сразу же уйти[/ex][/*][/m]
	[m3][*][ex][lang id=1033]you had better say it at once[/lang] — будет гораздо лучше, если вы сразу скажете об этом[/ex][/*][/m]
	[m2]11. [com][i]one had rather do smth than …[/i][/com] [trn]я /ты, он [p]и т. п.[/p]/ бы предпочёл, сделать что-л., чем[/trn] …[/m]
	[m3][*][ex][lang id=1033]I had rather do it myself[/lang] — я предпочёл бы сделать это сам, я лучше сделал бы это сам[/ex][/*][/m]
	[m3][*][ex][lang id=1033]I'd rather not go[/lang] — я предпочёл бы не ходить[/ex][/*][/m]
	[m2]12. [com][i][lang id=1033]one had as soon /[p]уст.[/p] as lief/ do smth[/lang][/i][/com] [trn]я /ты, он [p]и т. п.[/p]/ бы скорее предпочёл сделать что-л.[/trn][/m]
	[m3][*][ex][lang id=1033]I had as soon start at once[/lang] — я скорее предпочёл бы отправиться сразу[/ex][/*][/m]
	[m2]13. 1) [com][i][lang id=1033]one won't /can't/ have smth[/lang][/i] ([i][lang id=1033]done[/lang][/i])[/com] [trn]не допускать чего-л., не терпеть чего-л.[/trn][/m]
	[m3][*][ex][lang id=1033]I won't have such conduct[/lang] — я не потерплю такого поведения[/ex][/*][/m]
	[m3][*][ex][lang id=1033]I cannot have it in my house[/lang] — я не могу допустить этого в своём доме[/ex][/*][/m]
	[m3][*][ex][lang id=1033]let us have no nonsense![/lang] — давайте без глупостей![/ex][/*][/m]
	[m4]2) [com][i][lang id=1033]one won't /can't/ have smb do /doing/ smth[/lang][/i][/com] [trn]не позволить, кому-л. делать что-л.[/trn][/m]
	[m3][*][ex][lang id=1033]I won't have you say /saying/ such things[/lang] — я не допущу, чтобы вы говорили подобные вещи[/ex][/*][/m]
	[m2]14. [com][i]to have it that …[/i][/com] [trn]говорить, утверждать, что …; гласить[/trn][/m]
	[m3][*][ex][lang id=1033]the newspapers have it that …[/lang] — газеты утверждают, что …[/ex][/*][/m]
	[m3][*][ex][lang id=1033]he will have it that …[/lang] — он считает /настаивает на том/, что …[/ex][/*][/m]
	[m3][*][ex][lang id=1033]rumour has it that …[/lang] — ходят слухи, что …[/ex][/*][/m]
	[m3][*][ex][lang id=1033]as Shakespeare has it[/lang] — как говорит Шекспир[/ex][/*][/m]
	[m2][c][b]Ⅲ А[/b][/c][/m]
	[m2]1. [com][i]в сочетании с последующим инфинитивом выражает долженствование[/i][/com][/m]
	[m3][*][ex][lang id=1033]one has to do smth[/lang] — я /ты, он [p]и т. п.[/p]/ должен сделать что-л.[/ex][/*][/m]
	[m3][*][ex][lang id=1033]she has to keep the house[/lang] — ей приходится вести хозяйство[/ex][/*][/m]
	[m3][*][ex][lang id=1033]he has (got) to help us[/lang] — ему придётся нам помочь, он должен нам помочь[/ex][/*][/m]
	[m3][*][ex][lang id=1033]you will have to wait a moment[/lang] — вам придётся обождать минутку[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the money has to be paid[/lang] — эти деньги придётся заплатить /нужно уплатить, должны быть выплачены/[/ex][/*][/m]
	[m3][*][ex][lang id=1033]they had to suspend payment[/lang] — им пришлось приостановить платежи[/ex][/*][/m]
	[m3][*][ex][lang id=1033]you don't have to get so excited[/lang] — не нужно так волноваться[/ex][/*][/m]
	[m3][*][ex][lang id=1033]you don't have to apologize[/lang] — можете не извиняться, совершенно не нужно извиняться[/ex][/*][/m]
	[m2]2. [com][i]в сочетании с существительным означает единичный акт или кратковременное действие, соответствующее значению существительного[/i][/com][/m]
	[m3][*][ex][lang id=1033]to have a swim \[a shave, a wash, a walk, a dance, a smoke\][/lang] — поплавать \[побриться, помыться, погулять, потанцевать, покурить\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]to have a look[/lang] — взглянуть[/ex][/*][/m]
	[m3][*][ex][lang id=1033]let me have a look \[a try\][/lang] — дайте мне взглянуть \[попробовать\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]to have a fall[/lang] — упасть[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to have a bath \[a shower\][/lang] — принять ванну \[душ\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]to have a game[/lang] — сыграть партию[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to have a word with smb[/lang] — поговорить с кем-л.[/ex][/*][/m]
	[m2]3. [com][i][lang id=1033]have got[/lang][/i][/com] [p]см.[/p] <<get>> II, III А 1[/m]
	[m2][c][b]Ⅲ Б[/b][/c][/m]
	[m2]1. [com][i]вспомогательный глагол, служит для образования форм перфекта[/i][/com][/m]
	[m2]1):[/m]
	[m3][*][ex][lang id=1033]he has read this book[/lang] — он прочёл /читал/ эту книгу[/ex][/*][/m]
	[m3][*][ex][lang id=1033]how long have they known each other?[/lang] — как давно они знакомы /знают друг друга/?[/ex][/*][/m]
	[m3][*][ex][lang id=1033]by spring we shall have finished it[/lang] — к весне мы закончим это[/ex][/*][/m]
	[m3][*][ex][lang id=1033]you ought to have done it[/lang] — вам следовало /надлежало/ это сделать[/ex][/*][/m]
	[m3][*][ex][lang id=1033]it's silly not to have gone after having accepted the invitation[/lang] — глупо было не ходить, раз вы приняли приглашение[/ex][/*][/m]
	[m3][*][ex][lang id=1033]you haven't swept the room. — I have![/lang] — ты не подметал пол. — Нет, подметал![/ex][/*][/m]
	[m3][*][ex][lang id=1033]he hasn't been to England before, has he?[/lang] — он (ведь) раньше /прежде/ не бывал в Англии, не так ли?[/ex][/*][/m]
	[m3][*][ex][lang id=1033]you've forgotten your gloves. — So I have![/lang] — вы забыли перчатки. — Действительно![/ex][/*][/m]
	[m4]2) [p]эмоц.-усил.[/p] [com]([i]выделяется интонационно[/i])[/com]:[/m]
	[m3][*][ex][lang id=1033]well, you have grown![/lang] — как ты вырос!, ну и вырос же ты![/ex][/*][/m]
	[m3][*][ex][lang id=1033]had I seen him?![/lang] — видел ли я его?!, ну конечно же, я его видел![/ex][/*][/m]
	[m3][*][ex][lang id=1033]she has frequently dreamt about the past, has Joan![/lang] — Джоан очень, очень часто вспоминала о прошлом[/ex][/*][/m]
	[m4]3) [com]([i]в условных предложениях[/i])[/com]:[/m]
	[m3][*][ex][lang id=1033]had one …[/lang] — если бы я /ты, он [p]и т. п.[/p]/ …[/ex][/*][/m]
	[m3][*][ex][lang id=1033]had they searched more closely, they would have found what they wanted[/lang] — если бы они искали (по)внимательнее, они бы нашли то, что им было нужно[/ex][/*][/m]
	[m2]2. [com][i]вспомогательный глагол, служит для образования [p]эмоц.-усил.[/p] конструкций и альтернативных вопросов вне перфекта[/i][/com]:[/m]
	[m3][*][ex][lang id=1033]she had a good time, had Mary![/lang] — и здорово же провела Мэри время![/ex][/*][/m]
	[m3][*][ex][lang id=1033]he had a sister, hadn't he?[/lang] — у него ведь была сестра, не так ли?[/ex][/*][/m]
	[m3][p]♦[/p][/m]
	[m3][*][ex][lang id=1033]to have it[/lang] — получить удар, понести наказание[/ex][/*][/m]
	[m3][*][ex][lang id=1033]I've had it! Let's stop and rest[/lang] — всё, больше не могу! Надо передохнуть[/ex][/*][/m]
	[m3][*][ex][lang id=1033]he decided that he had had it and quit the stage[/lang] — он решил, что с него довольно /хватит/, и ушёл со сцены[/ex][/*][/m]
	[m3][*][ex][lang id=1033]let him have it![/lang] — а) покажи ему!, задай ему взбучку!; б) скажи ему откровенно, что ты о нём думаешь![/ex][/*][/m]
	[m3][*][ex][lang id=1033]to let smb have it in the face[/lang] — дать кому-л. по физиономии[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to have had it[/lang] — дойти до ручки[/ex][/*][/m]
	[m3][*][ex][lang id=1033]he has had it[/lang] — а) теперь ему конец /крышка/; теперь он пропал; б) он безнадёжно отстал[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to have it away /off/ with smb[/lang] — [p]сл.[/p] иметь половые сношения с кем-л., «трахаться»[/ex][/*][/m]
	[m3][*][ex][lang id=1033]have it your own way[/lang] — делай /поступай/ как хочешь /как знаешь/[/ex][/*][/m]
	[m3][*][ex][lang id=1033]and there you have …[/lang] — и вот каков …[/ex][/*][/m]
	[m3][*][ex][lang id=1033]there you have the man[/lang] — вот какой он человек, вот полюбуйтесь на него[/ex][/*][/m]
	[m3][*][ex][lang id=1033]have done![/lang] — перестань!, хватит![/ex][/*][/m]
	[m3][*][ex][lang id=1033]and what have you[/lang] — и так далее, и всё в таком роде[/ex][/*][/m]
	[m3][*][ex][lang id=1033]pens, pencils and what have you[/lang] — ручки, карандаши и всё такое прочее /и так далее/[/ex][/*][/m]
	[m3][*][ex][lang id=1033]he had one on me[/lang] — он меня надул /обошёл/[/ex][/*][/m]