	[m0][b]Ⅰ[/b] \[[t]rʌn[/t]\] [p]n[/p][/m]
	[m2][c][b]Ⅰ[/b][/c][/m]
	[m2]1. 1) [trn]бег, пробег[/trn][/m]
	[m3][*][ex][lang id=1033]at a run[/lang] — бегом \[[p]см.[/p] [p]тж[/p] [p]♦[/p]\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]to come up at a run[/lang] — подбежать[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to cross exposed areas at a run[/lang] — [p]воен.[/p] преодолевать открытые участки перебежками[/ex][/*][/m]
	[m3][*][ex][lang id=1033]on the run[/lang] — а) на ходу, в движении; [lang id=1033]to be on the run all day[/lang] — быть весь день в бегах; б) второпях; \[[p]см.[/p] [p]тж[/p] 2) [c gray][i]{{[p]}}и{{[/p]}}[/i][/c] 3)\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]to keep smb on the run[/lang] — а) не давать кому-л. остановиться; б) не давать кому-л. покоя[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to break into a run[/lang] — побежать, пуститься бегом[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to make a run for it[/lang] — а) броситься куда-л. со всех ног; б) сделать перебежку куда-л. [com]([i]под пулями[/i] [p]и т. п.[/p])[/com][/ex][/*][/m]
	[m3][*][ex][lang id=1033]he took a short run and cleared the fence[/lang] — он разбежался и перепрыгнул через забор[/ex][/*][/m]
	[m3][*][ex][lang id=1033]there was no run left in me[/lang] — я больше не мог /у меня больше не было сил/ бежать[/ex][/*][/m]
	[m4]2) [trn]бегство; беспорядочное отступление[/trn][/m]
	[m3][*][ex][lang id=1033]to be on the run[/lang] — поспешно отступать, бежать \[[p]см.[/p] [p]тж[/p] 1) [c gray][i]{{[p]}}и{{[/p]}}[/i][/c] 3)\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]we have the enemy on the run[/lang] — мы обратили врага в бегство[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to keep the enemy on the run[/lang] — [p]воен.[/p] не давать противнику закрепляться [com]([i]в ходе преследования[/i])[/com][/ex][/*][/m]
	[m4]3) [trn]побег; нахождение в бегах[/trn][/m]
	[m3][*][ex][lang id=1033]the criminal was on the run[/lang] — преступник был в бегах \[[p]см.[/p] [p]тж[/p] 1) [c gray][i]{{[p]}}и{{[/p]}}[/i][/c] 2)\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]he is on the run from the police[/lang] — он скрывается /бегает/ от полиции[/ex][/*][/m]
	[m4]4) [trn]короткая прогулка [com]([i]пешком, на лошади[/i] [p]и т. п.[/p])[/com]; пробежка[/trn][/m]
	[m3][*][ex][lang id=1033]to go for a run[/lang] — а) пробежаться; б) проехаться [com]([i]в автомобиле, на лошади[/i] [p]и т. п.[/p])[/com][/ex][/*][/m]
	[m3][*][ex][lang id=1033]to go for a short run before breakfast[/lang] — а) немного пробежаться /сделать небольшую пробежку/ перед завтраком; б) совершить небольшую [com]([i]автомобильную, верховую[/i] [p]и т. п.[/p])[/com] прогулку перед завтраком[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to give smb a run[/lang] — дать пробежаться[/ex][/*][/m]
	[m3][*][ex][lang id=1033]I was giving my dog a run in the park[/lang] — я пустил свою собаку побегать в парке[/ex][/*][/m]
	[m2]2. [trn]короткая поездка[/trn][/m]
	[m3][*][ex][lang id=1033]a run to Paris[/lang] — кратковременная поездка в Париж[/ex][/*][/m]
	[m3][*][ex][lang id=1033]good run![/lang] — счастливого пути![/ex][/*][/m]
	[m2]3. [trn]рейс, маршрут[/trn][/m]
	[m3][*][ex][lang id=1033]ship's run[/lang] — маршрут /рейс/ корабля[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the boat was taken off its usual run[/lang] — судно было снято со своего обычного рейса[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the milkman has finished his run[/lang] — разносчик молока всех обслужил[/ex][/*][/m]
	[m2]4. 1) [trn]переход[/trn][/m]
	[m3][*][ex][lang id=1033]trial run[/lang] — испытательный пробег \[[p]см.[/p] [p]тж[/p] II 1\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]a day's run[/lang] — день пути[/ex][/*][/m]
	[m3][*][ex][lang id=1033]it is a quick run from Glasgow[/lang] — это недалеко от Глазго[/ex][/*][/m]
	[m3][*][ex][lang id=1033]it is two hours' run from London[/lang] — это находится в двух часах езды от Лондона[/ex][/*][/m]
	[m4]2) [p]ж.-д.[/p] [trn]перегон, прогон[/trn][/m]
	[m4]3) [p]ав.[/p] [trn]полёт; перелёт[/trn][/m]
	[m3][*][ex][lang id=1033]we had a good run[/lang] — полёт проходил хорошо[/ex][/*][/m]
	[m2]5. 1) [trn]пройденное расстояние; отрезок пути[/trn][/m]
	[m4]2) [p]ж.-д.[/p] [trn]пробег[/trn] [com]([i]локомотива, вагона[/i])[/com][/m]
	[m4]3) [p]ав.[/p] [trn]отрезок трассы[/trn][/m]
	[m2]6. [p]ав.[/p] [trn]пробег [com]([i]при посадке[/i])[/com]; разбег[/trn] [com]([i]при взлёте[/i])[/com][/m]
	[m2]7. 1) [trn]тропа[/trn] [com]([i]проложенная животными[/i])[/com][/m]
	[m3][*][ex][lang id=1033]a buffalo run[/lang] — буйволова тропа[/ex][/*][/m]
	[m4]2) [trn]колея[/trn] [com]([i]след от транспорта[/i])[/com][/m]
	[m2]8. [trn]период, отрезок [com]([i]времени[/i])[/com], полоса[/trn][/m]
	[m3][*][ex][lang id=1033]a run of success \[of good luck\][/lang] — полоса успеха \[везения /удачи/\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]a run of ill luck[/lang] — несчастливая полоса, полоса невезения[/ex][/*][/m]
	[m3][*][ex][lang id=1033]a long run of power[/lang] — долгое пребывание у власти[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to have a long run[/lang] — долго идти (на сцене)[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the play had a short run[/lang] — эта пьеса шла недолго[/ex][/*][/m]
	[m2]9. 1) [trn]направление[/trn][/m]
	[m3][*][ex][lang id=1033]the run of the mountains is S.W.[/lang] — горы тянутся на юго-запад[/ex][/*][/m]
	[m4]2) [p]геол.[/p] [trn]направление рудной жилы[/trn][/m]
	[m2]10. [trn]партия[/trn] [com]([i]изделий[/i])[/com][/m]
	[m2]11. [trn]тираж[/trn] [com]([i]книги[/i] [p]и т. п.[/p])[/com][/m]
	[m3][*][ex][lang id=1033]a run of three thousand (copies)[/lang] — тираж в три тысячи (экземпляров)[/ex][/*][/m]
	[m2]12. [p]спорт.[/p] [com]([i]в крикете и бейсболе[/i])[/com][/m]
	[m4]1) [trn]единица счёта[/trn][/m]
	[m4]2) [trn]перебежка[/trn][/m]
	[m3][*][ex][lang id=1033]to make six runs[/lang] — сделать шесть перебежек[/ex][/*][/m]
	[m4]3) [trn]очко за перебежку[/trn][/m]
	[m2]13. 1) [trn]стадо[/trn] [com]([i]животных[/i])[/com][/m]
	[m4]2) [trn]стая[/trn] [com]([i]птиц[/i])[/com][/m]
	[m4]3) [trn]косяк[/trn] [com]([i]рыбы[/i])[/com][/m]
	[m2]14. [p]карт.[/p] [trn]ряд, серия[/trn][/m]
	[m3][*][ex][lang id=1033]a run of cards[/lang] — карты одной масти, идущие подряд по достоинству; «стрит» [com]([i]в покере[/i])[/com][/ex][/*][/m]
	[m3][*][ex][lang id=1033]a run of three[/lang] — три карты одной масти подряд[/ex][/*][/m]
	[m2]15. [trn]средний тип, сорт [c gray][i]{{[p]}}или{{[/p]}}[/i][/c] разряд[/trn][/m]
	[m3][*][ex][lang id=1033]the general run of smth[/lang] — что-л. обычное /среднее/[/ex][/*][/m]
	[m3][*][ex][lang id=1033]an ordinary run of cloth[/lang] — обыкновенный /стандартный/ сорт ткани[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the common /general, ordinary/ run of men[/lang] — обыкновенные люди[/ex][/*][/m]
	[m3][*][ex][lang id=1033]out of the run[/lang] — необыкновенный, из ряда вон выходящий, незаурядный[/ex][/*][/m]
	[m3][*][ex][lang id=1033]above the ordinary run of mankind[/lang] — необыкновенный, незаурядный[/ex][/*][/m]
	[m3][*][ex][lang id=1033]not like the common run of girls[/lang] — не такая, как все девушки[/ex][/*][/m]
	[m2]16. [trn]спрос[/trn][/m]
	[m3][*][ex][lang id=1033]a run on rubber \[on a book\][/lang] — большой спрос на резину \[на книгу\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]to have a general run[/lang] — пользоваться широким спросом[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the book had a considerable run[/lang] — книга пользовалась спросом; книга хорошо распродавалась[/ex][/*][/m]
	[m3][*][ex][lang id=1033]a run on the bank[/lang] — [p]ком.[/p] наплыв в банк требований о возвращении вкладов, массовое изъятие вкладов из банка[/ex][/*][/m]
	[m2]17. [p]разг.[/p] [trn]разрешение, право пользоваться[/trn] [com]([i]чем-л.[/i])[/com][/m]
	[m3][*][ex][lang id=1033]to have the run of smb's house[/lang] — иметь право распоряжаться в чьём-л. доме[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to give smb the (free) run of one's house \[books\][/lang] — разрешить кому-л. (свободно, беспрепятственно) распоряжаться /пользоваться/ своим домом \[своими книгами\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]I had the run of a well-stocked library[/lang] — в моём полном распоряжении оказалась богатая библиотека[/ex][/*][/m]
	[m2]18. 1) [trn]загон[/trn] [com]([i]для овец[/i] [p]и т. п.[/p])[/com][/m]
	[m4]2) [trn]вольер[/trn] [com]([i]для кур[/i] [p]и т. п.[/p])[/com][/m]
	[m4]3) [p]австрал.[/p] [trn]пастбище, [p]особ.[/p] овечье[/trn][/m]
	[m4]4) [p]австрал.[/p] [trn]скотоводческая ферма[/trn][/m]
	[m2]19. [p]амер.[/p] [trn]ручей, поток[/trn][/m]
	[m2]20. 1) [trn]сильный прилив, приток[/trn] [com]([i]воды[/i] [p]и т. п.[/p])[/com][/m]
	[m4]2) [p]амер.[/p] [trn]ток [com]([i]жидкости[/i])[/com]; истечение[/trn][/m]
	[m3][*][ex][lang id=1033]the first run of the sugar maple[/lang] — сок сахарного клёна первого сбора[/ex][/*][/m]
	[m2]21. [trn]уклон, трасса[/trn][/m]
	[m2]22. [trn]обвал, оползень[/trn][/m]
	[m2]23. [trn]труба, жёлоб, лоток[/trn] [com]([i]для воды[/i])[/com][/m]
	[m2]24. [trn]длина[/trn] [com]([i]провода, труб[/i])[/com][/m]
	[m3][*][ex][lang id=1033]a 500 ft run of pipe[/lang] — пятисотфутовый отрезок трубы; труба длиной в пятьсот футов[/ex][/*][/m]
	[m2]25. [trn]размер[/trn] [com]([i]стиха[/i])[/com][/m]
	[m2]26. 1) [trn]ход рыбы на нерест[/trn][/m]
	[m4]2) [trn]нерестящаяся рыба[/trn][/m]
	[m2]27. [trn]марш[/trn] [com]([i]лестницы[/i])[/com][/m]
	[m2]28. [p]мор.[/p] [trn]кормовое заострение[/trn] [com]([i]корпуса[/i])[/com][/m]
	[m2]29. [p]муз.[/p] [trn]рулада[/trn][/m]
	[m2][c][b]Ⅱ[/b][/c][/m]
	[m2]1. [trn]ход, работа, действие[/trn] [com]([i]мотора, машины[/i])[/com][/m]
	[m3][*][ex][lang id=1033]test /trial/ run[/lang] — испытание [com]([i]машины, оборудования[/i] [p]и т. п.[/p])[/com] \[[p]см.[/p] [p]тж[/p] I 4, 1)\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]an experimental run to test the machinery[/lang] — опытный /пробный/ запуск агрегата[/ex][/*][/m]
	[m2]2. [trn]течение, ход[/trn] [com]([i]событий[/i] [p]и т. п.[/p])[/com][/m]
	[m3][*][ex][lang id=1033]the run of the disease[/lang] — ход /течение/ болезни[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the usual /ordinary/ run of things[/lang] — обычное положение вещей[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the run of the market[/lang] — [p]ком.[/p] общая тенденция рыночных цен[/ex][/*][/m]
	[m2]3. [trn]демонстрирование, показ, просмотр[/trn] [com]([i]фильма, спектакля[/i])[/com][/m]
	[m3][*][ex][lang id=1033]the first run of the film[/lang] — премьера кинофильма, выпуск кинофильма на экран[/ex][/*][/m]
	[m2]4. [trn]провоз[/trn] [com]([i]контрабанды[/i])[/com][/m]
	[m2]5. [p]ав.[/p] [trn]заход на цель[/trn] [com]([p]тж[/p] [lang id=1033]bombing run[/lang])[/com][/m]
	[m3][*][ex][lang id=1033]to enter the run[/lang] — начинать заход на цель[/ex][/*][/m]
	[m2]6. [p]амер.[/p] [trn]спустившаяся петля[/trn] [com]([i]на чулке[/i])[/com][/m]
	[m2]7. [trn]серия[/trn] [com]([i]измерений[/i])[/com][/m]
	[m3][p]♦[/p][/m]
	[m3][*][ex][lang id=1033]at a run[/lang] — подряд, один за другим \[[p]см.[/p] [p]тж[/p] I 1, 1)\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]in the long run[/lang] — в конце концов; в конечном счёте; в общем[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to go with a run[/lang] — [p]≈[/p] идти как по маслу[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to come down with a run[/lang] — стремительно падать[/ex][/*][/m]
	[m3][*][ex][lang id=1033]prices \[temperature\] came down with a run[/lang] — цены \[температура\] резко упали \[упала\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]to give smb /to let smb have/ a good run for his money[/lang] — а) предоставить кому-л. все удовольствия на свете ([p]обыкн.[/p] [p]ирон.[/p]); б) заставить кого-л. побегать, поволноваться [p]и т. п.[/p][/ex][/*][/m]
	[m3][*][ex][lang id=1033]it's all in the day's run[/lang] — это всё обычно, мы ко всему этому привыкли[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the run of one's teeth[/lang] — бесплатное питание [com]([p]обыкн.[/p] [i]за проделанную работу[/i])[/com][/ex][/*][/m]
	[m0][b]Ⅱ[/b] \[[t]rʌn[/t]\] [p]a[/p][/m]
	[m2]1. [trn]жидкий; расплавленный; растопленный[/trn][/m]
	[m3][*][ex][lang id=1033]run butter[/lang] — топлёное масло[/ex][/*][/m]
	[m2]2. [trn]вылитый в расплавленном состоянии; литой[/trn][/m]
	[m3][*][ex][lang id=1033]run metal[/lang] — литьё[/ex][/*][/m]
	[m2]3. [trn]отцеженный, отфильтрованный[/trn][/m]
	[m3][*][ex][lang id=1033]run honey[/lang] — чистый мёд [com]([i]отделённый от сот[/i])[/com][/ex][/*][/m]
	[m2]4. [p]разг.[/p] [trn]контрабандный[/trn][/m]
	[m2]5. [trn]нерестящийся[/trn][/m]
	[m3][*][ex][lang id=1033]run fish[/lang] — рыба, пришедшая в пресную воду на нерест[/ex][/*][/m]
	[m2]6. [p]спец.[/p] [trn]мягкий[/trn][/m]
	[m3][*][ex][lang id=1033]run coal[/lang] — мягкий [c gray][i]{{[p]}}или{{[/p]}}[/i][/c] сыпучий уголь; мягкий битуминозный уголь; рядовой уголь[/ex][/*][/m]
	[m2]7. [p]диал.[/p] [trn]свернувшийся, скисший[/trn] [com]([i]о молоке[/i])[/com][/m]
	[m0][b]Ⅲ[/b] \[[t]rʌn[/t]\] [p]v[/p] [com]([lang id=1033]ran, run[/lang])[/com][/m]
	[m2][c][b]Ⅰ[/b][/c][/m]
	[m2]1. [trn]бежать, бегать[/trn][/m]
	[m3][*][ex][lang id=1033]to run fast \[slowly, as hard as one can, like a deer\][/lang] — бегать быстро \[медленно, изо всех сил, как олень\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run a mile[/lang] — пробежать милю \[[p]ср.[/p] [p]тж[/p] II А 6, 2)\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run oneself out of breath[/lang] — задохнуться от бега[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run up and down the stairs[/lang] — бегать вверх и вниз по лестнице[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run upstairs[/lang] — побежать наверх[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run down a hill[/lang] — сбежать с холма[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run up and down the street[/lang] — бегать взад и вперёд по улице[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run about the streets \[the fields\][/lang] — бегать /носиться/ по улицам \[по полям\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run across the street[/lang] — перебежать (через) улицу[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run out of the room[/lang] — выбегать из комнаты[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run at smb's heels[/lang] — бежать рядом [com]([i]о собаке[/i])[/com][/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run past smb[/lang] — пробежать мимо кого-л.[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run after smb[/lang] — а) бежать за кем-л.; [lang id=1033]run after him[/lang] — беги за ним!, догони его!; б) ухаживать, «бегать» за кем-л.[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run after men[/lang] — бегать за мужчинами[/ex][/*][/m]
	[m3][*][ex][lang id=1033]she is very much run after[/lang] — за ней многие ухаживают[/ex][/*][/m]
	[m3][*][ex][lang id=1033]run after smth[/lang] — бежать за чем-л.[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run after a bus[/lang] — бежать вдогонку за автобусом[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run for smb[/lang] — сбегать за кем-л.[/ex][/*][/m]
	[m3][*][ex][lang id=1033]run for the doctor![/lang] — беги за врачом![/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run to smb for help[/lang] — побежать к кому-л. за помощью[/ex][/*][/m]
	[m3][*][ex][lang id=1033]we ran to her aid[/lang] — мы бросились к ней на помощь[/ex][/*][/m]
	[m3][*][ex][lang id=1033]she always runs to me in case of trouble[/lang] — когда у неё неприятности, она всегда прибегает /обращается/ ко мне[/ex][/*][/m]
	[m3][*][ex][lang id=1033]I must run now[/lang] — я должен уже бежать, мне пора (уходить)[/ex][/*][/m]
	[m2]2. [trn]гнать, подгонять[/trn][/m]
	[m3][*][ex][lang id=1033]he ran me breathless /off my logs, off my feet/[/lang] — он меня совершенно загнал, он меня загнал до изнеможения[/ex][/*][/m]
	[m3][*][ex][lang id=1033]don't run me too fast[/lang] — не гоните меня так быстро[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run cattle[/lang] — гнать скот [com]([i]на пастбище[/i])[/com][/ex][/*][/m]
	[m2]3. [trn]убегать, спасаться бегством[/trn] [com]([p]тж[/p] [lang id=1033]run away, run off[/lang])[/com][/m]
	[m3][*][ex][lang id=1033]to run from smb, smth[/lang] — убегать от кого-л., чего-л.[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the enemy ran[/lang] — враг обратился в бегство[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run for it[/lang] — [p]разг.[/p] удирать, спасаться, искать спасения в бегстве[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run for one's life /for dear life/[/lang] — [p]разг.[/p] бежать /удирать/ изо всех сил[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run before the sea[/lang] — [p]мор.[/p] уходить от волны[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run out of range[/lang] — [p]воен.[/p] выходить за пределы досягаемости [com]([i]огня[/i])[/com][/ex][/*][/m]
	[m2]4. 1) [trn]двигаться, катиться, скользить[/trn][/m]
	[m3][*][ex][lang id=1033]to run on rails[/lang] — ходить /двигаться/ по рельсам[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run off the rails[/lang] — а) сойти с рельсов [com]([i]о поезде, трамвае[/i])[/com]; б) сбиться с пути (праведного); в) [p]≈[/p] с катушек долой[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run past a signal[/lang] — проскочить светофор[/ex][/*][/m]
	[m3][*][ex][lang id=1033]motor-cars run along ordinary roads[/lang] — автомобили ездят по обычным дорогам[/ex][/*][/m]
	[m3][*][ex][lang id=1033]sledges run on snow[/lang] — сани скользят по снегу[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the ball ran past the hole[/lang] — мяч покатился мимо лунки [com]([i]в гольфе[/i])[/com][/ex][/*][/m]
	[m3][*][ex][lang id=1033]the drawer doesn't run easily[/lang] — ящик плохо выдвигается[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the ship ran before the wind[/lang] — а) корабль плыл с попутным ветром; б) [p]мор.[/p] корабль шёл на фордевинд[/ex][/*][/m]
	[m3][*][ex][lang id=1033]life runs smoothly for her[/lang] — её жизнь течёт гладко /спокойно/[/ex][/*][/m]
	[m4]2) [p]амер.[/p] [p]разг.[/p] [trn]катать в автомобиле[/trn] [com]([i]кого-л.[/i])[/com][/m]
	[m2]5. 1) [trn]ходить, следовать, курсировать, плавать[/trn][/m]
	[m3][*][ex][lang id=1033]to run from Moscow to St Petersburg[/lang] — следовать из Москвы в Санкт-Петербург[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run every three minutes \[daily\][/lang] — ходить каждые три минуты \[ежедневно\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run behind schedule[/lang] — опаздывать, отставать от расписания[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run on a regular service[/lang] — совершать регулярные рейсы[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the trains aren't running[/lang] — поезда не ходят[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the traffic runs day and night here[/lang] — здесь круглосуточное движение[/ex][/*][/m]
	[m3][*][ex][lang id=1033]this bus runs between Chicago and New York[/lang] — этот автобус курсирует между Чикаго и Нью-Йорком[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run straight for[/lang] — [p]мор.[/p] идти прямо в[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run off the course[/lang] — [p]мор.[/p] сбиваться с курса[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run in with the shore[/lang] — [p]мор.[/p] идти вдоль берега[/ex][/*][/m]
	[m4]2) [trn]двигаться, идти[/trn] [com]([i]с определённой скоростью[/i])[/com][/m]
	[m3][*][ex][lang id=1033]this train runs at 50 miles an hour[/lang] — этот поезд делает /идёт со скоростью/ пятьдесят миль в час[/ex][/*][/m]
	[m3][*][ex][lang id=1033]we run from forty to fifty miles a day[/lang] — мы проходим /делаем/ от сорока до пятидесяти миль в день[/ex][/*][/m]
	[m4]3) [trn]съездить [com]([i]куда-л.[/i])[/com] на короткий срок[/trn][/m]
	[m3][*][ex][lang id=1033]to run up to town (for a day or two)[/lang] — съездить в город [com]([p]обыкн.[/p] [i]в Лондон[/i])[/com] (на день-два)[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run up and visit smb[/lang] — съездить к кому-л. погостить[/ex][/*][/m]
	[m3][*][ex][lang id=1033]she ran up from Dorking almost daily[/lang] — она почти каждый день ездила из Доркинга (в Лондон)[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run down to the country[/lang] — съездить в деревню /в провинцию/ [com]([p]обыкн.[/p] [i]из Лондона[/i])[/com][/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run over to Paris[/lang] — съездить (ненадолго) в Париж[/ex][/*][/m]
	[m4]4) [p]ав.[/p] [trn]совершать пробег, разбег[/trn][/m]
	[m4]5) [p]ав.[/p] [trn]заходить на цель[/trn][/m]
	[m2]6. 1) [trn]бежать, лететь, протекать[/trn] [com]([i]о времени[/i])[/com][/m]
	[m3][*][ex][lang id=1033]time runs fast[/lang] — время бежит /летит/[/ex][/*][/m]
	[m3][*][ex][lang id=1033]his life had only a few hours to run[/lang] — ему оставалось жить всего несколько часов[/ex][/*][/m]
	[m4]2) [trn]идти, происходить[/trn] [com]([i]о событиях[/i] [p]и т. п.[/p])[/com][/m]
	[m3][*][ex][lang id=1033]things must run their course[/lang] — надо предоставить события их естественному ходу[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the war was running its appointed course[/lang] — война шла своим чередом[/ex][/*][/m]
	[m2]7. [trn]проноситься, мелькать[/trn][/m]
	[m3][*][ex][lang id=1033]thoughts run in /through/ one's head \[mind\][/lang] — мысли мелькают /проносятся/ в голове \[в уме\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]this tune runs in my head[/lang] — эта мелодия всё время звучит у меня в ушах[/ex][/*][/m]
	[m2]8. [trn](быстро) распространяться[/trn][/m]
	[m3][*][ex][lang id=1033]a rumour ran through the town[/lang] — по городу разнёсся /распространился, пополз/ слух[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the news ran like wildfire /like lightning/[/lang] — новость распространилась с молниеносной быстротой[/ex][/*][/m]
	[m3][*][ex][lang id=1033]a murmur ran through the ranks[/lang] — ропот пробежал /прокатился/ по рядам[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the fire ran through the building[/lang] — огонь охватил всё здание[/ex][/*][/m]
	[m3][*][ex][lang id=1033]a cheer ran down the line[/lang] — возгласы одобрения /крики ура/ прокатились по строю[/ex][/*][/m]
	[m3][*][ex][lang id=1033]a cold shiver ran down his spine[/lang] — холодная дрожь пробежала у него по спине[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the pain ran up his arm[/lang] — он почувствовал острую боль в руке[/ex][/*][/m]
	[m3][*][ex][lang id=1033]I felt the blood running to my head[/lang] — я почувствовал, как кровь ударила /бросилась/ мне в голову[/ex][/*][/m]
	[m2]9. 1) [trn]тянуться, простираться, расстилаться[/trn][/m]
	[m3][*][ex][lang id=1033]to run north and south[/lang] — тянуться /простираться/ на север и на юг[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the road runs across the plain[/lang] — дор[']о[/']га проходит по равнине[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the road runs up the hill[/lang] — дор[']о[/']га идёт в гору[/ex][/*][/m]
	[m3][*][ex][lang id=1033]a river that runs 200 miles[/lang] — река протяжённостью в двести миль[/ex][/*][/m]
	[m3][*][ex][lang id=1033]under the hill ran a deep ravine[/lang] — у подножия холма лежало глубокое ущелье[/ex][/*][/m]
	[m3][*][ex][lang id=1033]this line runs from … to …[/lang] — этот маршрут проходит от … до …, эта линия соединяет …[/ex][/*][/m]
	[m3][*][ex][lang id=1033]new streets will run here[/lang] — здесь будут новые улицы[/ex][/*][/m]
	[m3][*][ex][lang id=1033]down the centre ran a long table[/lang] — в середине находился длинный стол[/ex][/*][/m]
	[m3][*][ex][lang id=1033]a scar runs across his cheek[/lang] — у него шрам во всю щёку[/ex][/*][/m]
	[m4]2) [trn]ползти, виться[/trn] [com]([i]о растениях[/i])[/com][/m]
	[m3][*][ex][lang id=1033]a vine runs over the porch[/lang] — крыльцо увито виноградом[/ex][/*][/m]
	[m3][*][ex][lang id=1033]a rambling rose ran all over the wall[/lang] — роза оплетала всю стену[/ex][/*][/m]
	[m2]10. [trn]проводить, прокладывать[/trn][/m]
	[m3][*][ex][lang id=1033]to run a fence round a house[/lang] — обнести дом забором[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run boundary lines (on a map)[/lang] — проводить границы (на карте)[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run a contour[/lang] — обвести контур[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run a parallel (too far)[/lang] — проводить (слишком далёкие) параллели[/ex][/*][/m]
	[m2]11. 1) [trn]быть действительным на определённый срок[/trn][/m]
	[m3][*][ex][lang id=1033]this contract runs for seven years[/lang] — этот контракт действителен на семь лет[/ex][/*][/m]
	[m3][*][ex][lang id=1033]this bill ran thirty days[/lang] — этот вексель был сроком на 30 дней[/ex][/*][/m]
	[m3][*][ex][lang id=1033]this agreement has two years to run[/lang] — это соглашение действительно ещё на два года[/ex][/*][/m]
	[m4]2) [trn]распространяться на определённую территорию, действовать на определённой территории[/trn][/m]
	[m3][*][ex][lang id=1033]the King's laws do not run here[/lang] — королевские законы на эту местность не распространяются[/ex][/*][/m]
	[m3][*][ex][lang id=1033]so far as British justice runs[/lang] — там, где действует британское правосудие[/ex][/*][/m]
	[m4]3) [trn]иметь хождение[/trn] [com]([i]о деньгах[/i])[/com][/m]
	[m4]4) [trn]сопровождать в качестве непременного условия[/trn][/m]
	[m3][*][ex][lang id=1033]a right-of-way that runs with the land[/lang] — земля, через которую проходит полоса отчуждения [com]([i]шоссе[/i] [p]и т. п.[/p])[/com][/ex][/*][/m]
	[m2]12. 1) [trn]течь, литься, сочиться, струиться[/trn][/m]
	[m3][*][ex][lang id=1033]to run with sweat[/lang] — взмокнуть (от пота)[/ex][/*][/m]
	[m3][*][ex][lang id=1033]this river runs smoothly[/lang] — эта река течёт плавно /спокойно/[/ex][/*][/m]
	[m3][*][ex][lang id=1033]rivers run into the sea[/lang] — реки впадают в море[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the water is running into the bath[/lang] — вода льётся в ванну[/ex][/*][/m]
	[m3][*][ex][lang id=1033]wait till the water runs hot[/lang] — подожди, пока не пойдёт горячая вода[/ex][/*][/m]
	[m3][*][ex][lang id=1033]blood runs in veins[/lang] — кровь течёт по жилам[/ex][/*][/m]
	[m3][*][ex][lang id=1033]blood ran in torrents[/lang] — кровь текла /лилась/ ручьём[/ex][/*][/m]
	[m3][*][ex][lang id=1033]till the blood ran[/lang] — пока не потекла /не показалась/ кровь[/ex][/*][/m]
	[m3][*][ex][lang id=1033]tears ran down her cheeks[/lang] — слёзы текли /катились/ по её щекам /лицу/[/ex][/*][/m]
	[m3][*][ex][lang id=1033]her eyes ran with tears[/lang] — её глаза наполнились слезами; из её глаз потекли слёзы[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the floor was running with water[/lang] — пол был залит водой[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the kettle is beginning to run[/lang] — чайник закипает /льётся через край/[/ex][/*][/m]
	[m3][*][ex][lang id=1033]water ran off his raincoat[/lang] — с его плаща стекала вода[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the scolding ran off him like water off a duck's back[/lang] — его ругают, а с него как с гуся вода[/ex][/*][/m]
	[m4]2) [trn]протекать, течь[/trn][/m]
	[m3][*][ex][lang id=1033]this tap \[barrel, pen\] runs[/lang] — этот кран \[бочонок, эта ручка\] течёт[/ex][/*][/m]
	[m3][*][ex][lang id=1033]his nose was running, he was running at the nose[/lang] — у него текло из носу[/ex][/*][/m]
	[m3][*][ex][lang id=1033]his eyes run[/lang] — у него слезятся /гноятся/ глаза[/ex][/*][/m]
	[m3][*][ex][lang id=1033]an ulcer that runs[/lang] — кровоточащая язва[/ex][/*][/m]
	[m4]3) [trn]разливаться, расплываться[/trn][/m]
	[m3][*][ex][lang id=1033]the wine ran (all) over the table[/lang] — вино растеклось по (всему) столу[/ex][/*][/m]
	[m3][*][ex][lang id=1033]this ink does not run[/lang] — эти чернила не расплываются[/ex][/*][/m]
	[m4]4) [trn]таять, течь[/trn][/m]
	[m3][*][ex][lang id=1033]the ice-cream is beginning to run[/lang] — мороженое начинает таять[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the butter ran[/lang] — масло растаяло[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the candle ran[/lang] — свеча оплыла[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the wax melted and ran[/lang] — воск растаял и оплыл[/ex][/*][/m]
	[m4]5) [com]([lang id=1033]into[/lang])[/com] [trn]сливаться, переходить[/trn] [com]([i]во[/i] [p]что-л.[/p])[/com][/m]
	[m3][*][ex][lang id=1033]to run into one[/lang] — сливаться, объединяться воедино[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run into one another[/lang] — переходить один в другой, сливаться в одно[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the colours ran into one another[/lang] — цвета переходили один в другой[/ex][/*][/m]
	[m3][*][ex][lang id=1033]days ran into weeks[/lang] — из дней складывались недели[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the rooms ran one into the other[/lang] — комнаты были проходными[/ex][/*][/m]
	[m2]13. [trn]лить, наливать[/trn][/m]
	[m3][*][ex][lang id=1033]to run water into a glass[/lang] — налить воду в стакан[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run water into a bath-tub[/lang] — наливать воду в ванну, напускать ванну[/ex][/*][/m]
	[m3][*][ex][lang id=1033]streets run blood[/lang] — улицы были залиты кровью[/ex][/*][/m]
	[m2]14. 1) [trn]вращаться[/trn][/m]
	[m3][*][ex][lang id=1033]a wheel \[a spindle\] runs[/lang] — колесо \[шпиндель\] вращается[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run (up)on an axis[/lang] — а) вращаться вокруг оси; б) вращаться на оси[/ex][/*][/m]
	[m4]2) [com]([lang id=1033]on, upon[/lang])[/com] [trn]касаться[/trn] [com]([i]какой-л. темы[/i] [p]и т. п.[/p])[/com][/m]
	[m3][*][ex][lang id=1033]his mind kept running on the problem[/lang] — его мысли всё время вертелись вокруг этой проблемы; он всё время думал об этой проблеме[/ex][/*][/m]
	[m3][*][ex][lang id=1033]our talk /the conversation/ ran on recent events[/lang] — мы всё время говорили /разговор шёл/ о недавних событиях[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the whole argument runs on this point[/lang] — этот момент является центральным в споре[/ex][/*][/m]
	[m4]3) [com]([lang id=1033]over[/lang])[/com] [trn]касаться, слегка дотрагиваться до ([p]чего-л.[/p])[/trn][/m]
	[m3][*][ex][lang id=1033]her fingers ran over the keys of the piano[/lang] — её пальцы пробежали по клавишам рояля[/ex][/*][/m]
	[m2]15. [trn]гласить[/trn][/m]
	[m3][*][ex][lang id=1033]this clause runs[/lang] — этот пункт гласит[/ex][/*][/m]
	[m3][*][ex][lang id=1033]her telegram runs[/lang] — в её телеграмме говорится[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the letter ran thus[/lang] — в письме было изложено следующее[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the story runs that (the bank will close)[/lang] — говорят, что (банк закроется)[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the proverb runs like this[/lang] — вот как звучит эта пословица, эта пословица гласит[/ex][/*][/m]
	[m3][*][ex][lang id=1033]I forget how the poem runs[/lang] — я не могу точно припомнить это стихотворение[/ex][/*][/m]
	[m2]16. [trn]проходить; преодолевать[/trn] [com]([i]препятствие[/i])[/com][/m]
	[m3][*][ex][lang id=1033]to run a blockade[/lang] — прорывать блокаду[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run the guard[/lang] — проходить незамеченным мимо часового[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run rapids[/lang] — преодолевать пороги, проходить через пороги[/ex][/*][/m]
	[m2]17. [trn]линять[/trn][/m]
	[m3][*][ex][lang id=1033]colour that does not run[/lang] — нелинючая краска[/ex][/*][/m]
	[m2]18. [p]амер.[/p], [p]австрал.[/p] [trn]дразнить [com]([i]кого-л.[/i])[/com], приставать [com]([i]к кому-л.[/i])[/com], дёргать[/trn] [com]([i]кого-л.[/i])[/com][/m]
	[m2]19. [p]стр.[/p] [trn]покрывать штукатуркой[/trn][/m]
	[m3][*][ex][lang id=1033]to run a moulding[/lang] — вытягивать карниз шаблоном[/ex][/*][/m]
	[m2][c][b]Ⅱ А[/b][/c][/m]
	[m2]1. [trn]руководить [com]([i]учреждением[/i] [p]и т. п.[/p])[/com]; вести[/trn] [com]([i]дело, предприятие[/i] [p]и т. п.[/p])[/com][/m]
	[m3][*][ex][lang id=1033]to run a business[/lang] — вести дело, управлять предприятием[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run a factory[/lang] — управлять фабрикой, быть управляющим на фабрике[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run a theatre[/lang] — руководить театром, быть директором театра[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run the external affairs of the state[/lang] — руководить внешней политикой государства[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run the house (for smb)[/lang] — вести (чьё-л.) хозяйство[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run the show[/lang] — [p]разг.[/p] заправлять [com]([i]чем-л.[/i])[/com][/ex][/*][/m]
	[m3][*][ex][lang id=1033]who is running the show?[/lang] — [p]разг.[/p] кто здесь главный?[/ex][/*][/m]
	[m3][*][ex][lang id=1033]he is run by his secretary[/lang] — он под башмаком у своего секретаря[/ex][/*][/m]
	[m3][*][ex][lang id=1033]she runs the household[/lang] — она ведёт хозяйство[/ex][/*][/m]
	[m3][*][ex][lang id=1033]it is being run as a commercial enterprise[/lang] — это дело ведётся на коммерческой основе[/ex][/*][/m]
	[m2]2. 1) [trn]управлять [com]([i]автомобилем[/i])[/com]; водить[/trn] [com]([i]автобус[/i] [p]и т. п.[/p])[/com][/m]
	[m3][*][ex][lang id=1033]to run the engine[/lang] — запускать двигатель /мотор/[/ex][/*][/m]
	[m3][*][ex][lang id=1033]I run this machine[/lang] — я работаю на этой машине[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run a steamer[/lang] — водить пароход[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run a ship to New York[/lang] — вести корабль в Нью-Йорк[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run a car into a garage \[off the road\][/lang] — поставить автомобиль в гараж \[съехать на обочину\][/ex][/*][/m]
	[m4]2) [trn]водить корабль без конвоя[/trn] [com]([i]во время войны[/i])[/com][/m]
	[m2]3. [trn]ставить [com]([i]опыт[/i])[/com]; производить[/trn] [com]([i]испытания[/i])[/com][/m]
	[m3][*][ex][lang id=1033]he will run this experiment[/lang] — он поставит этот опыт[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run (the) trials[/lang] — [p]мор.[/p] а) производить ходовые испытания; б) проходить ходовые испытания[/ex][/*][/m]
	[m2]4. [trn]работать, действовать[/trn] [com]([i]о машине[/i])[/com][/m]
	[m3][*][ex][lang id=1033]to leave the engine running[/lang] — не выключать мотора[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the motor runs smoothly \[very nice\][/lang] — мотор работает ровно /спокойно/ \[хорошо\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]you mustn't let the machine run free /idle/[/lang] — ты не должен допускать, чтобы машина работала вхолостую /на холостом ходу/[/ex][/*][/m]
	[m3][*][ex][lang id=1033]an engine that runs at a very high speed[/lang] — мотор, работающий на больших скоростях[/ex][/*][/m]
	[m2]5. 1) [trn]пускать [com]([i]линию[/i])[/com]; открывать[/trn] [com]([i]трассу, сообщение[/i])[/com][/m]
	[m3][*][ex][lang id=1033]an express train runs between these cities[/lang] — между этими городами ходит поезд /есть железнодорожное сообщение/[/ex][/*][/m]
	[m4]2) [trn]отправлять [com]([i]автобусы[/i] [p]и т. п.[/p])[/com] на линию, по маршруту[/trn][/m]
	[m3][*][ex][lang id=1033]to run a bus every three minutes[/lang] — отправлять автобус через каждые три минуты[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run extra trains during the rush hours[/lang] — пускать дополнительные поезда в часы пик[/ex][/*][/m]
	[m2]6. 1) [trn]проводить[/trn] [com]([i]соревнования, бега, скачки[/i]; [p]тж[/p] [lang id=1033]run off[/lang])[/com][/m]
	[m3][*][ex][lang id=1033]the Derby was run in a snowstorm[/lang] — дерби проводилось во время снегопада[/ex][/*][/m]
	[m3][*][ex][lang id=1033]we are running a competition to find new dancers[/lang] — мы проводим конкурс, чтобы выявить новых танцоров[/ex][/*][/m]
	[m4]2) [trn]участвовать[/trn] [com]([i]в соревнованиях, в беге, в скачках[/i])[/com][/m]
	[m3][*][ex][lang id=1033]to run (in) a race[/lang] — участвовать в соревнованиях по бегу [c gray][i]{{[p]}}или{{[/p]}}[/i][/c] в скачках[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run (a race over) a mile[/lang] — участвовать в беге на одну милю \[[p]ср.[/p] [p]тж[/p] I 1\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]the cup will be run for tomorrow[/lang] — завтра будут проводиться соревнования на кубок[/ex][/*][/m]
	[m4]3) [trn]занимать место[/trn] [com]([i]в соревнованиях[/i] [p]и т. п.[/p])[/com][/m]
	[m3][*][ex][lang id=1033]to run second \[third\][/lang] — прийти вторым \[третьим\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]my horse ran last[/lang] — моя лошадь пришла последней /заняла последнее место/[/ex][/*][/m]
	[m3][*][ex][lang id=1033]also ran[/lang] — также участвовала [com]([i]в соревнованиях [p]и т. п.[/p] — о лошадях[/i])[/com], но не заняла призового места \[[p]см.[/p] [p]тж[/p] [p]♦[/p]\][/ex][/*][/m]
	[m2]7. 1) [trn]демонстрировать, показывать[/trn] [com]([i]пьесу, фильм[/i])[/com][/m]
	[m3][*][ex][lang id=1033]we ran this play six times[/lang] — мы показали эту пьесу 6 раз[/ex][/*][/m]
	[m4]2) [trn]идти[/trn] [com]([i]о пьесе, фильме[/i])[/com][/m]
	[m3][*][ex][lang id=1033]the play has been running for a year[/lang] — эта пьеса идёт (уже) год[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the film runs for nearly 2½ hours[/lang] — фильм идёт почти два с половиной часа[/ex][/*][/m]
	[m2]8. 1) [trn]перевозить, транспортировать[/trn] [com]([i]груз[/i])[/com][/m]
	[m3][*][ex][lang id=1033]to run a cargo of coffee[/lang] — перевозить груз кофе[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run smb into London[/lang] — отвезти кого-л. в Лондон[/ex][/*][/m]
	[m4]2) [trn]провозить контрабандой[/trn][/m]
	[m3][*][ex][lang id=1033]to run liquor \[drugs, arms\][/lang] — нелегально /контрабандой/ провозить спиртные напитки \[наркотики, оружие\][/ex][/*][/m]
	[m2]9. 1) [trn]преследовать, травить[/trn] [com]([i]зверя[/i] [p]и т. п.[/p])[/com][/m]
	[m3][*][ex][lang id=1033]to run a stag[/lang] — преследовать оленя[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run a fox five miles[/lang] — гнать лису 5 миль[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run a scent[/lang] — идти по следу[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run to earth[/lang] — а) загнать в нору; б) скрыться в нору; в) выследить; найти, обнаружить; настигнуть; [lang id=1033]I was run to earth by Ben[/lang] — Бен еле-еле разыскал меня; [lang id=1033]to run a quarry to earth[/lang] — настичь, жертву; г) спрятаться, притаиться[/ex][/*][/m]
	[m3][*][ex][lang id=1033]he ran the rumour to its source[/lang] — он докопался до источника этого слуха[/ex][/*][/m]
	[m4]2) [trn]преследовать[/trn] [com]([i]по суду[/i])[/com][/m]
	[m2]10. [trn]подвергаться[/trn] [com]([i]риску, опасности[/i])[/com][/m]
	[m3][*][ex][lang id=1033]to run risks /hazards, chances/[/lang] — рисковать[/ex][/*][/m]
	[m3][*][ex][lang id=1033]you run no risk of meeting him[/lang] — тебе не грозит опасность встретить его[/ex][/*][/m]
	[m3][*][ex][lang id=1033]we ran a chance of getting no dinner[/lang] — мы могли /нам грозило, мы рисковали/ остаться без обеда[/ex][/*][/m]
	[m3][*][ex][lang id=1033]you run the danger of being suspected of theft[/lang] — есть опасность, что вас заподозрят в краже[/ex][/*][/m]
	[m2]11. [trn]печатать, опубликовывать, помещать[/trn] [com]([i]в газете, журнале[/i])[/com][/m]
	[m3][*][ex][lang id=1033]to run a story on the third page[/lang] — помещать /давать/ рассказ на третьей странице[/ex][/*][/m]
	[m2]12. 1) [trn]баллотироваться[/trn] [com]([i]на пост[/i])[/com][/m]
	[m3][*][ex][lang id=1033]to run in an election[/lang] — баллотироваться на выборах[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run for parliament \[for office, for president\][/lang] — баллотироваться в парламент \[на [com]([i]какую-л.[/i])[/com] должность, на пост президента\][/ex][/*][/m]
	[m4]2) [trn]выставлять[/trn] [com]([i]кандидатуру[/i])[/com][/m]
	[m3][*][ex][lang id=1033]to run a candidate[/lang] — выставлять /выдвигать/ кандидата[/ex][/*][/m]
	[m3][*][ex][lang id=1033]who(m) will the Republicans run against the Democratic candidate?[/lang] — кого выставят республиканцы против кандидата (от) демократической партии?[/ex][/*][/m]
	[m2]13. [trn]выполнять[/trn] [com]([i]поручение[/i])[/com][/m]
	[m3][*][ex][lang id=1033]to run errands[/lang] — а) выполнять поручения; б) быть на посылках, на побегушках[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run messages[/lang] — быть посыльным, разносить телеграммы [p]и т. п.[/p][/ex][/*][/m]
	[m2]14. [trn]болтать; распускать[/trn] [com]([i]язык[/i])[/com][/m]
	[m3][*][ex][lang id=1033]how your tongue runs[/lang] — как ты (много) болтаешь[/ex][/*][/m]
	[m2]15. [trn]спускаться[/trn] [com]([i]о петле[/i])[/com][/m]
	[m3][*][ex][lang id=1033]silk stockings run[/lang] — на шёлковых чулках спускаются петли[/ex][/*][/m]
	[m3][*][ex][lang id=1033]her stocking ran[/lang] — у неё на чулке спустилась петля[/ex][/*][/m]
	[m2]16. [trn]смётывать [com]([i]платье[/i] [p]и т. п.[/p])[/com]; сшить на скорую руку[/trn] [com]([p]тж[/p] [lang id=1033]to run up[/lang])[/com][/m]
	[m2]17. [trn]идти[/trn] [com]([i]на нерест[/i])[/com][/m]
	[m3][*][ex][lang id=1033]the salmon runs every year[/lang] — сёмга нерестится каждый год[/ex][/*][/m]
	[m2]18. 1) [trn]плавить[/trn] [com]([i]металл[/i])[/com][/m]
	[m4]2) [trn]лить, отливать[/trn] [com]([i]металл[/i])[/com][/m]
	[m2]19. [trn]отставать[/trn] [com]([i]о коре деревьев[/i])[/com][/m]
	[m2]20. [trn]ударить [com]([i]по шару[/i])[/com], покатить[/trn] [com]([i]шар — в биллиарде[/i])[/com][/m]
	[m2]21. [p]диал.[/p][/m]
	[m4]1) [trn]скисать, свёртываться[/trn] [com]([i]о молоке[/i])[/com][/m]
	[m4]2) [trn]квасить, приводить к свёртыванию[/trn] [com]([i]молоко[/i])[/com][/m]
	[m2][c][b]Ⅱ Б[/b][/c][/m]
	[m2]1. [com][i][lang id=1033]to run across smb, smth[/lang][/i][/com] [trn]случайно встретить кого-л., что-л., случайно встретиться с кем-л., чем-л.; натолкнуться на кого-л., что-л.[/trn][/m]
	[m3][*][ex][lang id=1033]I ran across him in the street[/lang] — я случайно встретился /столкнулся/ с ним на улице[/ex][/*][/m]
	[m3][*][ex][lang id=1033]I ran across this quotation in a dictionary[/lang] — эта цитата попалась мне в словаре[/ex][/*][/m]
	[m2]2. [com][i][lang id=1033]to run against smth[/lang][/i][/com] [trn]наталкиваться, налетать, наскакивать на что-л., сталкиваться с чем-л.[/trn][/m]
	[m3][*][ex][lang id=1033]to run against a rock[/lang] — наскочить на скалу, удариться о скалу[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run (up) against difficulties[/lang] — столкнуться с трудностями[/ex][/*][/m]
	[m3][*][ex][lang id=1033]this runs against my interests[/lang] — это идёт вразрез с моими интересами[/ex][/*][/m]
	[m2]3. [com][i][lang id=1033]to run against smb[/lang][/i][/com] [trn]идти, действовать, выступать против кого-л.[/trn][/m]
	[m3][*][ex][lang id=1033]the statute runs against him[/lang] — закон против него[/ex][/*][/m]
	[m2]4. [com][i][lang id=1033]to run smth against smth[/lang][/i][/com] [trn]столкнуть что-л. с чем-л.; стукнуть что-л. обо что-л.[/trn][/m]
	[m3][*][ex][lang id=1033]to run one's head against a wall[/lang] — а) стукнуться головой о стену; б) прошибать лбом стену[/ex][/*][/m]
	[m2]5. [com][i][lang id=1033]to run smb, smth against smb[/lang][/i][/com] [trn]выдвигать кого-л., что-л. против кого-л.[/trn][/m]
	[m2]6. [com][i][lang id=1033]to run at smb, smth[/lang][/i][/com] [trn]нападать, набрасываться, накидываться на кого-л., что-л.[/trn][/m]
	[m3][*][ex][lang id=1033]to run at smth with a knife[/lang] — броситься на кого-л. с ножом[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run at the railings[/lang] — налететь на ограду[/ex][/*][/m]
	[m3][*][ex][lang id=1033]she ran at Laurie and gave him a squeeze[/lang] — она бросилась к Лори и обняла его[/ex][/*][/m]
	[m2]7. [trn][com][i][lang id=1033]to run into smth[/lang][/i][/com][/trn][/m]
	[m4]1) [trn]налетать, наскакивать, наталкиваться на что-л., сталкиваться с чем-л.[/trn][/m]
	[m3][*][ex][lang id=1033]to run into a wall \[into a tree, into a boulder\][/lang] — налететь на стену \[на дерево, на камень\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run into a gale[/lang] — [p]мор.[/p] попасть в шторм[/ex][/*][/m]
	[m3][*][ex][lang id=1033]climbing higher, we ran into thick mist[/lang] — поднявшись выше, мы попали в густой туман /оказались в густом тумане/[/ex][/*][/m]
	[m4]2) [trn]попадать в какое-л. положение[/trn][/m]
	[m3][*][ex][lang id=1033]to run into debt[/lang] — залезть в долги[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run into danger \[into mischief, into trouble\][/lang] — попасть в опасное положение \[в беду\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]we ran into a surprise[/lang] — нас ожидал сюрприз[/ex][/*][/m]
	[m3][*][ex][lang id=1033]we expect to run into a few snags before the machine is ready for production[/lang] — вполне возможно, что прежде чем машина будет готова к запуску в производство, в ней обнаружатся некоторые недоделки[/ex][/*][/m]
	[m4]3) [trn]достигать определённого количества, исчисляться определённой суммой[/trn][/m]
	[m3][*][ex][lang id=1033]to run into thousands[/lang] — исчисляться тысячами[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the damages ran into thousands[/lang] — компенсация за убытки исчислялась тысячами /достигала нескольких тысяч/ (фунтов)[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the book ran into six editions[/lang] — книга выдержала шесть изданий[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the ship runs into so many tons displacement[/lang] — [p]мор.[/p] корабль имеет водоизмещение, достигающее стольких-то тонн[/ex][/*][/m]
	[m2]8. [com][i][lang id=1033]to run into smb[/lang][/i][/com] [trn]случайно встретить кого-л., столкнуться с кем-л.[/trn][/m]
	[m3][*][ex][lang id=1033]to run into an old friend[/lang] — случайно встретить старого друга[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run slap into smb[/lang] — [p]разг.[/p] налететь на кого-л., столкнуться лицом к лицу с кем-л.[/ex][/*][/m]
	[m2]9. [trn][com][i][lang id=1033]to run smth, smb into smth[/lang][/i][/com][/trn][/m]
	[m4]1) [trn]втыкать, вгонять, вонзать что-л. во что-л.[/trn][/m]
	[m3][*][ex][lang id=1033]to run a splinter into one's finger[/lang] — загнать занозу в палец[/ex][/*][/m]
	[m4]2) [trn]вводить, ставить; кого-л. в что-л.[/trn][/m]
	[m3][*][ex][lang id=1033]to run smb into expense[/lang] — ввести кого-л. в расход[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run smb into difficulties[/lang] — поставить кого-л. в трудное положение[/ex][/*][/m]
	[m2]10. [com][i][lang id=1033]to run smth, smb into smth, smb[/lang][/i][/com] [trn]столкнуть что-л., кого-л. с чем-л., кем-л.; заставить что-л., кого-л. налететь, наскочить, натолкнуться на что-л., на кого-л.[/trn][/m]
	[m3][*][ex][lang id=1033]they ran him into the barb-wire fence[/lang] — они загнали его на забор из колючей проволоки[/ex][/*][/m]
	[m3][*][ex][lang id=1033]he lost control of the car and ran it into a lamp-post[/lang] — он потерял управление и врезался в фонарный столб[/ex][/*][/m]
	[m3][*][ex][lang id=1033]he ran me into a cop[/lang] — из-за него я нарвался на полицейского[/ex][/*][/m]
	[m2]11. [com][i][lang id=1033]to run on smth[/lang][/i] = [lang id=1033]to run upon smth[/lang][/com][/m]
	[m2]12. [com][lang id=1033]to run out of smth[/lang][/com] истощать запас чего-л.; иссякать [com]([i]о запасах[/i] [p]и т. п.[/p])[/com][/m]
	[m3][*][ex][lang id=1033]we've run out of typing paper[/lang] — у нас кончилась бумага для машинки[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run out of ammunition[/lang] — [p]воен.[/p] израсходовать боеприпасы[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run out of altitude[/lang] — [p]ав.[/p] терять высоту полёта[/ex][/*][/m]
	[m2]13. [com][i][lang id=1033]to run smth over smth, smb[/lang][/i][/com] [trn]проводить чем-л. по чему-л., кому-л.[/trn][/m]
	[m3][*][ex][lang id=1033]to run an iron over a cloth[/lang] — провести утюгом по скатерти[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run one's hand \[fingers\] (down \[up\]) over his face \[her\][/lang] — провести рукой \[пальцами\] (вниз \[вверх\]) по его лицу \[по ней\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run an eye over smth, smb[/lang] — окинуть взглядом, бегло осмотреть что-л., кого-л.[/ex][/*][/m]
	[m3][*][ex][lang id=1033]he ran a rapid eye over the papers[/lang] — он бросил быстрый взгляд на бумаги /газеты/, он быстро пробежал глазами бумаги /газеты/[/ex][/*][/m]
	[m2]14. [com][i][lang id=1033]to run smth through smth[/lang][/i][/com] [trn]продевать, пропускать что-л. через что-л.[/trn][/m]
	[m3][*][ex][lang id=1033]to run a thread through an eyelet[/lang] — продеть нитку в ушко /в петлю/[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run one's fingers \[a comb\] through one's \[smb's\] hair[/lang] — провести пальцами \[расчёской\] по своим \[по чьим-л.\] волосам[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run a pen \[a pencil\] through smth[/lang] — зачеркнуть /прочеркнуть, перечеркнуть/ что-л. ручкой \[карандашом\][/ex][/*][/m]
	[m2]15. [com][i][lang id=1033]to run smth through smb, to run smb through with smth[/lang][/i][/com] [trn]пронзать, прокалывать кого-л. чем-л.[/trn][/m]
	[m3][*][ex][lang id=1033]to run a sword through smb, to run smb through with a sword[/lang] — проколоть /проткнуть, пронзить/ кого-л. шпагой[/ex][/*][/m]
	[m2]16. [trn][com][i][lang id=1033]to run through smth[/lang][/i][/com][/trn][/m]
	[m4]1) [trn]бегло прочитывать /просматривать/ что-л.[/trn][/m]
	[m3][*][ex][lang id=1033]to run through the text \[papers\][/lang] — бегло /быстро/ просмотреть текст /бумаги/[/ex][/*][/m]
	[m4]2) [p]разг.[/p] [trn]повторять ([p]особ.[/p] вкратце)[/trn][/m]
	[m3][*][ex][lang id=1033]I'll just run through the main points of the subject[/lang] — разрешите вкратце напомнить главные разделы этой темы[/ex][/*][/m]
	[m3][*][ex][lang id=1033]would you mind running through your proposals?[/lang] — пожалуйста, перечислите вкратце ваши предложения[/ex][/*][/m]
	[m4]3) [trn]репетировать[/trn][/m]
	[m3][*][ex][lang id=1033]I'd like to run you through that scene you have with Ophelia[/lang] — я бы хотел повторить вашу сцену с Офелией[/ex][/*][/m]
	[m4]4) [trn]тратить[/trn][/m]
	[m3][*][ex][lang id=1033]to run through money /fortune/[/lang] — промотать деньги /состояние/[/ex][/*][/m]
	[m2]17. [trn][com][i][lang id=1033]to run over smth[/lang][/i][/com][/trn][/m]
	[m4]1) [trn]бегло просматривать, пробегать[/trn] [com]([p]что-л.[/p] [i]глазами[/i])[/com][/m]
	[m3][*][ex][lang id=1033]to run over a text \[one's part, the names\][/lang] — просматривать текст \[свою роль, список имён\][/ex][/*][/m]
	[m4]2) [trn]повторять[/trn][/m]
	[m3][*][ex][lang id=1033]to run over one's part[/lang] — повторить свою роль[/ex][/*][/m]
	[m3][*][ex][lang id=1033]we shall run it over together[/lang] — мы повторим это вместе[/ex][/*][/m]
	[m4]3) [trn]репетировать; прослушивать актёра, читающего роль[/trn][/m]
	[m3][*][ex][lang id=1033]just run over my lines with me before the rehearsal begins[/lang] — пожалуйста, послушайте мою роль, пока ещё не началась репетиция (всей пьесы)[/ex][/*][/m]
	[m2]18. [trn][com][i][lang id=1033]to run to smth[/lang][/i][/com][/trn][/m]
	[m4]1) [trn]тяготеть к чему-л., иметь склонность к чему-л.[/trn][/m]
	[m3][*][ex][lang id=1033]to run to fat[/lang] — а) быть предрасположенным к полноте; б) [p]разг.[/p] толстеть, жиреть; в) превращаться в жир[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run to sentiment[/lang] — а) быть склонным к сентиментальности; б) быть сентиментальным[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run to extremes[/lang] — впадать в крайность[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run to any length /to anything/[/lang] — пойти на что угодно[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run to forgery[/lang] — пойти на подделку [com]([i]подписи, документов[/i])[/com][/ex][/*][/m]
	[m3][*][ex][lang id=1033]it won't run to that[/lang] — до этого не дойдёт[/ex][/*][/m]
	[m3][*][ex][lang id=1033]they run to big noses in that family[/lang] — в этом семействе много носатых[/ex][/*][/m]
	[m4]2) [trn]достигать[/trn] [com]([i]суммы, цифры[/i])[/com][/m]
	[m3][*][ex][lang id=1033]the increase may run to ten thousand pounds[/lang] — увеличение может достигнуть суммы в десять тысяч фунтов[/ex][/*][/m]
	[m3][*][ex][lang id=1033]that will run to a pretty penny[/lang] — это влетит /встанет/ в копеечку[/ex][/*][/m]
	[m3][*][ex][lang id=1033]the book runs to over 300 pages[/lang] — в книге более трёхсот страниц[/ex][/*][/m]
	[m4]3) [trn]хватать, быть достаточным[/trn][/m]
	[m3][*][ex][lang id=1033]the money won't run to a car[/lang] — этих денег не хватит на машину[/ex][/*][/m]
	[m3][*][ex][lang id=1033]our fund won't run to a summer holiday[/lang] — наших денег не хватит на летний отдых[/ex][/*][/m]
	[m3][*][ex][lang id=1033]I can't run to that[/lang] — я не могу себе этого позволить[/ex][/*][/m]
	[m2]19. [com][i][lang id=1033]to run[/lang][/i] ([i][lang id=1033]up[/lang][/i])[i][lang id=1033]on smth[/lang][/i][/com] [trn]неожиданно, внезапно встретиться с чем-л., натолкнуться, наскочить на что-л.[/trn][/m]
	[m3][*][ex][lang id=1033]to run (up)on a rock[/lang] — наскочить на скалу[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run (up)on rocks[/lang] — а) потерпеть крушение; б) натолкнуться на непреодолимые препятствия[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run on a mine[/lang] — [p]мор.[/p] наскочить на мину[/ex][/*][/m]
	[m2]20. [com][i][lang id=1033]to run smth[/lang][/i] ([i][lang id=1033]up[/lang][/i])[i][lang id=1033]on smth[/lang][/i][/com] [trn]натолкнуть на что-л., заставить наехать на что-л.[/trn][/m]
	[m3][*][ex][lang id=1033]to run a ship (up)on a reef[/lang] — посадить корабль на рифы[/ex][/*][/m]
	[m2]21. [com][i][lang id=1033]to run smb up /over, down/ to some place[/lang][/i][/com] [trn]отвезти кого-л. куда-л.[/trn][/m]
	[m3][*][ex][lang id=1033]to run smb up to town[/lang] — отвезти кого-л. в город [com]([p]обыкн.[/p] [i]в Лондон[/i])[/com][/ex][/*][/m]
	[m3][*][ex][lang id=1033]I could run you down to Dorking[/lang] — я мог бы отвезти вас в Доркинг[/ex][/*][/m]
	[m2]22. [com][i][lang id=1033]to run with smb[/lang][/i][/com] [p]преим.[/p] [p]амер.[/p] [trn]общаться с кем-л.; водить компанию с кем-л.[/trn][/m]
	[m3][*][ex][lang id=1033]he ran with a wild crowd when he was young[/lang] — в молодости он водил дружбу с гуляками[/ex][/*][/m]
	[m3][*][ex][lang id=1033]a ram running with ewes[/lang] — баран, пасущийся с овечками[/ex][/*][/m]
	[m2]23. [com][i][lang id=1033]to run counter to smth[/lang][/i][/com] [trn]противоречить, идти вразрез с чем-л.[/trn][/m]
	[m3][*][ex][lang id=1033]the situation runs counter to ordinary logic[/lang] — эта ситуация несовместима с простой логикой[/ex][/*][/m]
	[m2][c][b]Ⅲ А[/b][/c][/m]
	[m2][com][i]как глагол-связка в составном именном сказуемом[/i][/com][/m]
	[m2]1. [trn]становиться, делаться[/trn][/m]
	[m3][*][ex][lang id=1033]to run cold[/lang] — похолодеть[/ex][/*][/m]
	[m3][*][ex][lang id=1033]his blood ran cold[/lang] — у него кровь застыла в жилах[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run dry[/lang] — а) высыхать; [lang id=1033]the river ran dry[/lang] — река высохла /пересохла/; б) выдыхаться, иссякать[/ex][/*][/m]
	[m3][*][ex][lang id=1033]my imagination ran dry[/lang] — моё воображение истощилось, моя фантазия иссякла[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run high[/lang] — а) подниматься [com]([i]о приливе[/i])[/com]; б) волноваться [com]([i]о море[/i])[/com]; [lang id=1033]the sea runs high[/lang] — море волнуется; в) разгораться [com]([i]о страстях[/i])[/com]; [lang id=1033]passions /feelings/ ran high[/lang] — страсти разгорались /бушевали/; г) возрастать [com]([i]о ценах[/i])[/com][/ex][/*][/m]
	[m3][*][ex][lang id=1033]the tide is running strong[/lang] — вода быстро прибывает, прилив быстро поднимается[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run low[/lang] — а) понижаться, опускаться; б) истощаться, иссякать, быть на исходе; кончаться[/ex][/*][/m]
	[m3][*][ex][lang id=1033]supplies ran low[/lang] — запасы были на исходе /кончались/[/ex][/*][/m]
	[m3][*][ex][lang id=1033]his funds \[stores\] are running low[/lang] — его фонды \[запасы\] подходят к концу[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run short[/lang] — истощаться, подходить к концу[/ex][/*][/m]
	[m3][*][ex][lang id=1033]drinking water was running short[/lang] — питьевая вода подходила к концу[/ex][/*][/m]
	[m3][*][ex][lang id=1033]I have run short of money, my money has run short[/lang] — у меня кончились деньги, мне не хватило денег[/ex][/*][/m]
	[m3][*][ex][lang id=1033]we are running short of time[/lang] — у нас остаётся мало времени[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run hot[/lang] — нагреваться[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run mad[/lang] — сходить с ума[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run wild[/lang] — а) бурно разрастаться; [lang id=1033]the garden is running wild[/lang] — сад зарастает; б) расти без присмотра; не получить образования; в) разойтись, разыграться; [lang id=1033]his imagination ran wild[/lang] — его воображение разыгралось; г) не знать удержу, пуститься во все тяжкие[/ex][/*][/m]
	[m2]2. [trn]быть, являться[/trn][/m]
	[m3][*][ex][lang id=1033]the apples \[pears\] run large /big/ this year[/lang] — в этом году яблоки \[груши\] крупные[/ex][/*][/m]
	[m3][*][ex][lang id=1033]trout run to a good size[/lang] — форель бывает крупная[/ex][/*][/m]
	[m3][*][ex][lang id=1033]they run in all shapes[/lang] — они бывают разной формы /всех видов, всякие, разные/[/ex][/*][/m]
	[m3][*][ex][lang id=1033]prices run from ten shillings to a pound[/lang] — цены колеблются от десяти шиллингов до одного фунта[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run in the blood /in the family/[/lang] — быть наследственным[/ex][/*][/m]
	[m3][*][ex][lang id=1033]it runs in his blood[/lang] — это у него в крови[/ex][/*][/m]
	[m3][*][ex][lang id=1033]courage \[the collecting spirit, fondness for music\] runs in the family[/lang] — храбрость \[страсть к коллекционированию, любовь к музыке\] — это у них семейное[/ex][/*][/m]
	[m2]3. [trn]иметь[/trn][/m]
	[m3][*][ex][lang id=1033]to run (a) temperature[/lang] — иметь (высокую) температуру[/ex][/*][/m]
	[m3][*][ex][lang id=1033]I think I am running a temperature[/lang] — мне кажется, что у меня (поднимается) температура[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run a fever[/lang] — лихорадить[/ex][/*][/m]
	[m3][*][ex][lang id=1033]he always runs a fever if he gets his feet wet[/lang] — его всегда лихорадит, если он промочит ноги[/ex][/*][/m]
	[m3][p]♦[/p][/m]
	[m3][*][ex][lang id=1033]an also ran[/lang] — неудачник \[[p]см.[/p] [p]тж[/p] II А 6, 3)\][/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run the streets[/lang] — быть беспризорником[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run riot[/lang] — [p]см.[/p] <<riot>> I [p]♦[/p][/ex][/*][/m]
	[m3][*][ex][lang id=1033]her report runs on different lines[/lang] — её доклад построен по-другому[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run the show[/lang] — распоряжаться; быть во главе; [p]≈[/p] командовать парадом[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run false[/lang] — идти наперерез [com]([i]при охоте на зверя[/i])[/com][/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run smth close[/lang] — быть почти равным [com]([i]по качеству[/i] [p]и т. п.[/p])[/com][/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run smb close[/lang] — а) быть чьим-л. опасным соперником; б) быть почти равным кому-л.[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run to cover[/lang] — уйти от /избежать/ опасности; принять меры предосторожности[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to cut and run[/lang] — убегать; удирать, спасаться бегством; бежать со всех ног; улепётывать[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run foul (of)[/lang] — а) [p]мор.[/p] столкнуться [com]([i]с другим судном[/i])[/com]; б) [p]ист.[/p] брать на абордаж; в) поссориться; вступить в конфликт[/ex][/*][/m]
	[m3][*][ex][lang id=1033]they ran foul of the law[/lang] — они оказались в неладах с законом[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run oneself \[smb\] into the ground[/lang] — измотать себя \[кого-л.\]; совершенно измочалить себя [com]([i]работой, спортом[/i] [p]и т. п.[/p])[/com][/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run smb ragged[/lang] — [p]см.[/p] <<ragged>> [p]♦[/p][/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run to seed[/lang] — [p]см.[/p] <<seed>> I [p]♦[/p][/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run a mile (from)[/lang] — бегать от кого-л.; изо всех сил избегать кого-л.[/ex][/*][/m]
	[m3][*][ex][lang id=1033]he was a bore whom everyone ran a mile from[/lang] — он был занудой, от которого все старались избавиться[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run it /things/ fine[/lang] — иметь в обрез [com]([i]времени, денег[/i])[/com][/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run out of steam[/lang] — [p]см.[/p] <<steam>> I 3[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run rings round[/lang] — [p]см.[/p] <<ring>>[sup]1[/sup] I [p]♦[/p][/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run before the hounds[/lang] — забегать вперед, опережать события[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run the wrong hare[/lang] — просчитаться, ошибиться в расчётах; пойти по ложному следу[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run aground[/lang] — [p]мор.[/p] а) сесть [c gray][i]{{[p]}}или{{[/p]}}[/i][/c] посадить на мель; [lang id=1033]to run a ship aground[/lang] — посадить корабль на мель; б) выбрасываться на берег[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run ashore[/lang] — [p]мор.[/p] выбрасываться на берег; приткнуться к берегу[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run a line \[a rope\] ashore[/lang] — передать /бросить/ конец \[трос\] на берег[/ex][/*][/m]
	[m3][*][ex][lang id=1033]to run with the hare and hunt with the hounds[/lang] — [p]посл.[/p] [p]≈[/p] служить и нашим и вашим; вести двойную игру[/ex][/*][/m]
	[m3][*][ex][lang id=1033]he who runs may read[/lang] — [p]посл.[/p] всякий поймёт, всякому доступно /понятно/ [com]([i]о чём-л. лёгком, доступном для понимания[/i])[/com][/ex][/*][/m]