	[m0]\[[t]ˈskɔːrɪŋ[/t]\] [p]n[/p][/m]
	[m1]1. [p]тех.[/p] [trn]задиры[/trn][/m]
	[m1]2. = <<score>> I 2, 1)[/m]
	[m2][*][ex][lang id=1033]scoring table[/lang] — оценочная таблица[/ex][/*][/m]
	[m1]3. [p]с.-х.[/p] [trn]апробация[/trn] [com]([i]зерна[/i])[/com][/m]
	[m1]4. [p]кино[/p] [trn]озвучивание[/trn][/m]
	[m1]5. [p]спорт.[/p] [trn]забивание голов; набирание очков[/trn][/m]
	[m2][*][ex][lang id=1033]scoring chance[/lang] — голевая ситуация[/ex][/*][/m]
	[m2][*][ex][lang id=1033]scoring run[/lang] — изменение счёта [com]([i]в ходе игры[/i])[/com][/ex][/*][/m]