	[m0]\[[t]ˈsʌmwʌn, ˈsʌmwən[/t]\] [p]indef[/p] [p]pron[/p][/m]
	[m1][trn]кто-то, кто-нибудь, кто-либо[/trn][/m]
	[m2][*][ex][lang id=1033]someone else[/lang] — кто-то другой[/ex][/*][/m]
	[m2][*][ex][lang id=1033]someone else's[/lang] — чужой, не свой[/ex][/*][/m]
	[m2][*][ex][lang id=1033]someone or other[/lang] — тот или иной; кто-нибудь, кто-либо[/ex][/*][/m]
	[m2][*][ex][lang id=1033]someone has to lock up the house[/lang] — кто-нибудь /кто-то/ должен запереть дом[/ex][/*][/m]